### ISSUE TITLE
Reimbursement for Gas Costs for setting up Aragon DAO

### ISSUE THREAD

**Issue by chrishobcroft** [ethereum-cat-herders/funding#1]
And here are the txns for gas costs for setting up a DAO:

https://etherscan.io/tx/0xa47beff28d29799e672d77accf7d58aeb5497d6488dd7f3b9dbddd4101dd28c1
https://etherscan.io/tx/0x270822820a70ce3fec1011760034e21aeabac760d0fed235de75eceb2a8a63e5

Total 0.032666865 Ether

Please reimburse to 0x70564145fA8e8A15348EF0190e6B7c07A2120462

**Comment by lrettig** [comment]
Approved. @chrishobcroft we don't hold any ETH (https://etherscan.io/address/0x68085e7f88e90fa9247489c83fab30b177ebccb3). Are you okay being reimbursed in DAI at the current spot rate?

**Comment by chrishobcroft** [comment]
Sure.

**Comment by lrettig** [comment]
Done: https://etherscan.io/tx/0xa0dd43bb3db5ac9e6259b92abb04774f53e712007a3fd4ef22edd53afbac48db

0.032666865 ETH @ 0.00746392 ETH/DAI = 4.37663653951275 DAI
