### ISSUE TITLE
Funding for note-taking for core devs call #62

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/funding#10]
50 DAI to @DBrettRobertson for https://github.com/ethereum/pm/pull/103. Brett what's the address for payment?

**Comment by DBrettRobertson** [comment]
dbrettrobertson.gitcoin.eth

**Comment by lrettig** [comment]
Submitted tx 18 to the multisig, @Souptacular / @CPSTL could you please double-check and confirm? Thanks

**Comment by CPSTL** [comment]
Confirmed.

**Comment by lrettig** [comment]
Still need to record in the accounting spreadsheet

**Comment by lrettig** [comment]
Confirmed that this was added to the spreadsheet, thanks!
