### ISSUE TITLE
Funding for Eth2 call #48 notes

### ISSUE THREAD

**Issue by pggallagher** [ethereum-cat-herders/funding#101]
Payable to padpad.eth (preferable in eth if possible?)

**Comment by poojaranjan** [comment]
To be paid in ETH, please add the rate at the time of submission of the PR. 
Ref: https://github.com/ethereum-cat-herders/funding/issues/86 for understanding.

**Comment by pggallagher** [comment]
eh, I’m too lazy so DAI is fine :p thank you

**Comment by poojaranjan** [comment]
100 DAI transaction initiated.
Multisg transaction id # 86.

**Comment by poojaranjan** [comment]
Transaction completed and recorded.
