### ISSUE TITLE
Funding for ETH2 49

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#104]
PR: [eth2.0-pm/pull/185](https://github.com/ethereum/eth2.0-pm/pull/185)
Payable to: wschwab.eth

Amount: 0.2837 ETH (100 DAI at time of PR)
Proof of PR time:

![eth2_pr_oct_1](https://user-images.githubusercontent.com/31592931/94836511-bc9d8500-041b-11eb-8cae-284ceeae0448.png)

Proof of price at time of PR:

![eth_price_oct_1](https://user-images.githubusercontent.com/31592931/94836559-c7f0b080-041b-11eb-98c5-2dfa93771b51.png)

100 / 352.44 = 0.2837

Thanks!

**Comment by poojaranjan** [comment]
bundling with #103 
(0.2837+0.2813) ETH = 0.565 ETH
multisig tx id 89
https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by wschwab** [comment]
Received. Thanks!
