### ISSUE TITLE
Funding for ACD 97

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#107]
[PR](https://github.com/ethereum/pm/pull/214)
![preview](https://imgur.com/oHjDhfe.png)

Amount: 0.282 ETH (100$)
![preview](https://imgur.com/spkTV10.png)

ETH address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
ECH multisig id - 98
Tx completed: https://etherscan.io/tx/0x513a91262d04f5df510dde169bc1081e7ebca26d2df17c60dca5c3a9fd2002a1
