### ISSUE TITLE
Funding for EIP1559 outreach

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#108]
Payable to: wschwab.eth

Amount: 225 DAI (4.5 hrs @ 50 DAI/hr)
My hours are visible on the outreach spreadsheet

Previous conversation leaned towards payment only being available in DAI (not ETH). If there is a way to receive ETH, please let me know, and we'll discuss what conversion rate should be used.

Thanks!

**Comment by poojaranjan** [comment]
ECH multisig id: 97
Tx completed - https://etherscan.io/tx/0x1db001f2e6ab1117094c091d9ddd89019014b2425d2b6e979f38b80efc88990f
