### ISSUE TITLE
Funding for 1559 5 and ECH 43

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#113]
[ECH43](https://github.com/ethereum-cat-herders/PM/pull/141)
![ECH](https://imgur.com/KiuK824.png)

[1559](https://github.com/ethereum/pm/pull/216)
![1559](https://imgur.com/tGI7fVL.png)

Amount: 0.3675 ETH ($150)
![amount](https://imgur.com/C7Z02Di.png)

Address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Please create two separate requests with value of ETH on respective day of submission of Pull Request.

**Comment by poojaranjan** [comment]
@alita-moore a gentle reminder :)

**Comment by alita-moore** [comment]
Ah good point! Thanks for the reminder @poojaranjan 😊

**Comment by alita-moore** [comment]
@poojaranjan [1559](https://github.com/ethereum-cat-herders/funding/issues/120) [ech](https://github.com/ethereum-cat-herders/funding/issues/119)
