### ISSUE TITLE
Funding for 1559 outreach (Oct 16 - Oct 31)

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#117]
**For**: 1559 outreach efforts (biweekly submission)

**Effort**: 4 hrs

**Amount**: 200 DAI

**Ref**: 
- Sheet: https://docs.google.com/spreadsheets/d/1z5VMyNKbIdvdo-N7VMb8AIeQgy8SvewKSdf0fAzqp9w/edit#gid=0

**Wallet**: 0x5d357A824EFA2F57D8B723662D9e02F98Ba2CbFc

cc: @timbeiko

**Comment by timbeiko** [comment]
Transaction 99 in the multisig needs one more confirmation.

**Comment by poojaranjan** [comment]
Funds received, thanks!
