### ISSUE TITLE
Funding for ECH 43

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#119]
(actually created on oct 18th)  
[ECH43](https://github.com/ethereum-cat-herders/PM/pull/141)
![ECH](https://imgur.com/KiuK824.png)

created on Oct18th (not the one highlighted, but above)  
![ech](https://i.imgur.com/7A5YWbA.png)

amount: 0.13211 ETH (50$)
address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Created tx #103 om the multisg for #119 & #120

**Comment by Souptacular** [comment]
Confirmed that this was correctly executed in Gnosis Safe.
