### ISSUE TITLE
Funding for note-taking for Eth2.0-implementers-calls #19 

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#12]
note-taking for Eth2.0 implementer's call #19 [notes](https://github.com/ethereum/eth2.0-pm/pull/50)

**Comment by DBrettRobertson** [comment]
Funding does not appear to be available from Ethereum 2.0 for this call. Suggest Ethereum Cat Herders fund @poojaranjan for these notes.  

NOTE: All future Ethereum 2.0 notes have been funded through Gitcoin and these notes slipped through the cracks.

**Comment by Souptacular** [comment]
@DBrettRobertson I am confused a little bit. Does this mean we fund the note taking for this issue, but not future ones?

**Comment by poojaranjan** [comment]
@Souptacular To my knowledge Eth 2.0 is now taking care of all notes by Gitcoin bounty managed by Eth2 team. @DBrettRobertson can add more info.

**Comment by DBrettRobertson** [comment]
> @DBrettRobertson I am confused a little bit. Does this mean we fund the note taking for this issue, but not future ones?

Correct, unfortunately this call slipped through the cracks and never formed part of the new Gitcoin bounty funding by the Eth 2.0.

**Comment by poojaranjan** [comment]
Sure, thanks. Adding it to [Agenda](https://github.com/ethereum-cat-herders/PM/issues/89)

**Comment by poojaranjan** [comment]
Approved in [ECH Meeting 20](https://github.com/ethereum-cat-herders/PM/blob/master/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%2020.md)

**Comment by lrettig** [comment]
What's the amount?

**Comment by poojaranjan** [comment]
100 DAI

**Comment by lrettig** [comment]
@poojaranjan destination address?

**Comment by poojaranjan** [comment]
0xf13e477365B0FAa64130DA2FF663aAb20d32d929

**Comment by lrettig** [comment]
Submitted to multisig, @CPSTL @timbeiko @Souptacular please double-check and confirm if all looks good!

Ref: https://etherscan.io/tx/0x10198d33b57938e2a0232a63b2d354a45a0e0ecdc4c5fcedbd8f3384b39c62ae

**Comment by timbeiko** [comment]
Confirmed! You should have received the funds at the specified address. Thank you for your patience 😄 !
