### ISSUE TITLE
Funding for 1559 meeting 5

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#120]
[1559](https://github.com/ethereum/pm/pull/216)
![1559](https://imgur.com/tGI7fVL.png)

created on oct12th  
![value](https://i.imgur.com/7A5YWbA.png)

amount: 0.25830 ETH (100$)
address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Created tx #103 om the multisg for #119 & #120

**Comment by Souptacular** [comment]
Confirmed that this was correctly executed in Gnosis Safe.
