### ISSUE TITLE
Funding for EIP IP Meeting # 19

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#121]
## **EIPIP Meeting 19**
* **PR**: https://github.com/ethereum-cat-herders/EIPIP/pull/40
* **Amount**: 100 DAI
* **Wallet**: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

Thank you

**Comment by poojaranjan** [comment]
multisig tx #106 created, need 1 more signature.

**Comment by Souptacular** [comment]
Confirmed that this was correctly executed in Gnosis Safe.
