### ISSUE TITLE
Funding for Eth2 meeting 52

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#125]
PR: https://github.com/ethereum/eth2.0-pm/pull/192

Payable to: `wschwab.eth`

Amount: 0.181047905 ETH (100 USD at the time of PR)

Proof of Price:
Time of PR:
![eth2_pr_nov_22](https://user-images.githubusercontent.com/31592931/99911474-56d3c800-2cfd-11eb-9646-38c81354833a.png)

Price at time of PR:
![eth_price_nov_22](https://user-images.githubusercontent.com/31592931/99911478-605d3000-2cfd-11eb-881e-83ff0223656f.png)

100 / 552.34 = 0.181047905

**Comment by poojaranjan** [comment]
Multisig tx #107 created, need one more approval.

**Comment by poojaranjan** [comment]
Tx completed
