### ISSUE TITLE
Funding for notes, Eth2 call 53

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#128]
PR: https://github.com/ethereum/eth2.0-pm/pull/195
- Payable to: `edson.eth`
- For amount: 100 DAI/USDC

**Comment by poojaranjan** [comment]
for ECH 47 & Eth2 53 notes

multisig tx. 115 created, need one more approval.

**Comment by Souptacular** [comment]
Approved tx 115.

https://etherscan.io/tx/0x97272e1b1de7a73a702fcfe94c2ffa1d790bd7d00d7bd65b64b9b29738fa20af
