### ISSUE TITLE
Funding for EIPIP Meeting #22

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#129]
- **Note:** [EIPIP Meeting 22](https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20022.md)
- **Amount:** 100 DAI/USDC
- **Wallet:** 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

Thank you

**Comment by poojaranjan** [comment]
for Eth2 54, EIP-1559 meeting 8, EIPIP 22, 

multisig transaction 116 created, need one more approval.

**Comment by Souptacular** [comment]
Approved tx 116.

https://etherscan.io/tx/0x8cc625bf1180387b182c5dd383943c3cbf84514fbda02019590b2a783f356aa4
