### ISSUE TITLE
Funding for notes, ACD 101

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#130]
PR: https://github.com/ethereum/pm/pull/233

payable to: `wschwab.eth`

amount: Even though these notes are generally bountied at 100DAI (or ETH equivalent), due to my turning them in exceptionally late (over 2.5 weeks late), I would like to only take the equivalent of 50DAI in ETH, which is: 0.079985922 ETH

Proof of price:
Time of PR (see time in top bar):
![pr_acd_dec_16](https://user-images.githubusercontent.com/31592931/102377610-8eb4ef00-3fcd-11eb-92e6-f9413a7eac72.png)

Price at time of PR:
![eth_price_dec_16](https://user-images.githubusercontent.com/31592931/102377684-9f656500-3fcd-11eb-8052-9ed83e487269.png)

50/625.11 = 0.079985922

**Comment by poojaranjan** [comment]
Created multisig tx 118, need one more approval.

**Comment by poojaranjan** [comment]
Completed: https://etherscan.io/tx/0xcecda3091a7e233e89af74d5fd0be41983587253fb6087cc61a326dea59700f2
