### ISSUE TITLE
Funding for ECH 46

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#138]
PR: https://github.com/ethereum-cat-herders/PM/pull/147
ECH / USD @ PR creation: 538.26

![image](https://i.imgur.com/Uo9DB34.png)

ETH Funding Request: $50 / 538.26 = 0.1858 ETH
address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Created multisig tx  127 for payment of #142 , #139 , #138, #140

**Comment by poojaranjan** [comment]
Transaction status - success.
