### ISSUE TITLE
Funding for ACD 100

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#139]
PR: https://github.com/ethereum/pm/pull/227
ECH / USD @ PR creation: 538.26

![image](https://i.imgur.com/Uo9DB34.png)

ETH Funding Request: $100 / 538.26 = 0.0929 ETH
address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Created multisig tx  127 for payment of #142 , #139 , #138, #140

**Comment by poojaranjan** [comment]
Transaction status - successful.
