### ISSUE TITLE
Funding ACD 102

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#140]
PR: https://github.com/ethereum/pm/pull/236
ECH / USD @ PR creation: $1,041.50

![image](https://i.imgur.com/e0n6Ko1.png)

ETH Funding Request: $100 / $1,041.50 = 0.0960 ETH
address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Created multisig tx  127 for payment of #142 , #139 , #138, #140

**Comment by poojaranjan** [comment]
Transaction status - success
