### ISSUE TITLE
Funding for EIPIP 24

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#142]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/49
![PR](https://i.imgur.com/6isubzF.png)

ETH to USD: $1226
![ETH TO USD](https://i.imgur.com/NvurlRa.png)

Amount: $100 / $1226 = 0.08157 ETH

Payable to: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Starting from Jan 2021, for EIPIP meeting notes, the bounty is 150 DAI and equivalent. Please update the funding request.

**Comment by alita-moore** [comment]
updated @poojaranjan!

**Comment by poojaranjan** [comment]
It appears, I misread the notes. Ref:

[![image](https://user-images.githubusercontent.com/29681685/105188457-ee894300-5b01-11eb-97d2-2777b607fe5d.png)](https://github.com/ethereum-cat-herders/PM/blob/master/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%20049.md#decision-items)

You were correct, apologies for the confusion. **The correct amount is 100 DAI or equivalent.** 

Can you please update it? I will proceed with the payment at the earliest after your confirmation. 

Thanks for your patience!

**Comment by poojaranjan** [comment]
Created multisig tx  127 for payment of #142 , #139 , #138, #140

**Comment by poojaranjan** [comment]
Transaction status - success
