### ISSUE TITLE
Funding for 1559 meeting notes 09

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#143]
- PR. : [1559 meeting notes 09](https://github.com/ethereum/pm/pull/240)
- Amount: 150 DAI/USDC
- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

Thank you

**Comment by poojaranjan** [comment]
Multisig tx 129 created

**Comment by poojaranjan** [comment]
Transaction status - success.
