### ISSUE TITLE
Funding for EIPIP meeting 25 notes

### ISSUE THREAD

**Issue by shanelightowler** [ethereum-cat-herders/funding#146]
PR. : [EIPIP meeting 25 notes](https://github.com/ethereum-cat-herders/EIPIP/pull/52)
Amount: 100 DAI/USDC
Wallet: 0x6030f4C1657b61dD2db605be4510E79F9bE141bb

**Comment by poojaranjan** [comment]
Funding for notes have been revised, please update the request as per the decision item.

![image](https://user-images.githubusercontent.com/29681685/106305849-378c7600-622b-11eb-97f3-95742f32e102.png)

**Comment by shanelightowler** [comment]
PR URL updated to https://github.com/ethereum-cat-herders/EIPIP/pull/52

**Comment by poojaranjan** [comment]
Multisig tx - 133 created, waiting on one more approval

**Comment by poojaranjan** [comment]
tx completed
