### ISSUE TITLE
Funding for ECH meeting #51 notes

### ISSUE THREAD

**Issue by shanelightowler** [ethereum-cat-herders/funding#150]
PR. : [ECH meeting 51 notes](https://github.com/ethereum-cat-herders/PM/pull/159)
Amount: 50 DAI/USDC
Wallet: 0x6030f4C1657b61dD2db605be4510E79F9bE141bb

**Comment by poojaranjan** [comment]
Created multisig tx for #151 & #150

**Comment by poojaranjan** [comment]
tx completed
