### ISSUE TITLE
Funding for Eth2 Implementers Call 57

### ISSUE THREAD

**Issue by shanelightowler** [ethereum-cat-herders/funding#151]
PR. : [Eth2 Call 57](https://github.com/ethereum/eth2.0-pm/pull/204)
Amount: 150 DAI/USDC
Wallet: 0x6030f4C1657b61dD2db605be4510E79F9bE141bb

**Comment by poojaranjan** [comment]
Created multisig tx for #51 & #50

**Comment by poojaranjan** [comment]
tx completed
