### ISSUE TITLE
ACD 105 Funding

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#152]
PR: https://github.com/ethereum/pm/pull/249

![pr](https://i.imgur.com/vQYgiqg.png)

ETH Price at PR open: $1,794.46

![eth price](https://i.imgur.com/RR0Je3m.png)

Requested ETH = ($150) / ($1,794.46) = 0.08359 ETH

Address = address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Created multisig tx. Waiting on another approval.

**Comment by poojaranjan** [comment]
tx completed
