### ISSUE TITLE
ACD  meeting 106 Funding

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#154]
- PR  [link](https://github.com/ethereum/pm/pull/253)
- Amount: 175 DAI/USDC
- wallet 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Multisig tx created for #154 , #157 , #158

Total amount = 50+100+175 =325 DAI/USDC

cc: @timbeiko for ACD meeting

**Comment by poojaranjan** [comment]
tx. completed.
