### ISSUE TITLE
Notes: ECH meeting 53

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#160]
PR: https://github.com/ethereum-cat-herders/PM/pull/164
- Payable to: `edson.eth`
- For amount: $50 in ETH ($1681.57 USD currently). (fees are high, would be trading to ETH anyway)

**Comment by poojaranjan** [comment]
Edson, 

Generally, we prefer to get a screenshot with a timestamp, but if it's not available, could you please add a screenshot of the PR date and the price of ETH on that date from google or any other source?

Sample PR for your reference: #148

**Comment by edsonayllon** [comment]
@poojaranjan just do usdc

**Comment by edsonayllon** [comment]
<img width="946" alt="Screen Shot 2021-03-15 at 6 21 22 PM" src="https://user-images.githubusercontent.com/34966228/111228847-e8b85700-85b2-11eb-936e-2bc92d9ed82a.png">

**Comment by poojaranjan** [comment]
Price in ETH = 50/1671 = 0.02992 ETH
multisig tx 73 created, need one more approval.

**Comment by poojaranjan** [comment]
tx. completed.
