### ISSUE TITLE
Funding for notes - ACD #107

### ISSUE THREAD

**Issue by shanelightowler** [ethereum-cat-herders/funding#161]
PR: https://github.com/ethereum/pm/pull/272
Payable to: 0x6030f4C1657b61dD2db605be4510E79F9bE141bb
Amount: $150 in DAI

**Comment by poojaranjan** [comment]
Please add the amount in ETH

**Comment by shanelightowler** [comment]
@poojaranjan I have amended the request to DAI.

**Comment by poojaranjan** [comment]
This meeting's payout is 150 DAI.

**Comment by poojaranjan** [comment]
Multisig tx . 74 created for #162 & #161

**Comment by poojaranjan** [comment]
> Multisig tx . 74 created for #162 & #161.

Tx. 74 could not be completed. Ref: https://etherscan.io/tx/0x6ce70ac609134ac48c2d21eface3701b8a1540a72bf92e7cd0ab4f080243b6b3 

 Multisig tx. 75 initiated.

**Comment by poojaranjan** [comment]
Tx completed
