### ISSUE TITLE
Funding for notes - EIP-1559 community call

### ISSUE THREAD

**Issue by shanelightowler** [ethereum-cat-herders/funding#162]
PR: ethereum/pm#272
Payable to: 0x6030f4C1657b61dD2db605be4510E79F9bE141bb
Amount: $150 in DAI

**Comment by poojaranjan** [comment]
Shane, 

Generally, we prefer to get a screenshot with a timestamp, but if it's not available, could you please add a screenshot of the PR date and the price of ETH on that date from google or any other source?

PR for your reference: https://github.com/ethereum-cat-herders/funding/issues/148

**Comment by shanelightowler** [comment]
@poojaranjan I have amended the request to DAI.

**Comment by poojaranjan** [comment]
Multisig tx . 74 created for #162 & #161. 
One more approval required.

**Comment by poojaranjan** [comment]
> Multisig tx . 74 created for #162 & #161.
> One more approval required.

Tx. 74 could not be completed. Ref: https://etherscan.io/tx/0x6ce70ac609134ac48c2d21eface3701b8a1540a72bf92e7cd0ab4f080243b6b3 

 Multisig tx. 75 initiated.

**Comment by poojaranjan** [comment]
Tx completed.
