### ISSUE TITLE
ETH 2 call 58

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#163]
- PR. : [Eth 2.0 call 58](https://github.com/ethereum/eth2.0-pm/pull/207)
 
![image](https://user-images.githubusercontent.com/74140118/111194315-161bf980-85e1-11eb-831c-cba9a85252ec.png)

- Amount: 0.00053*150 =0.0795 ETH
- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
created multisig tx 72, waiting on one more approval.

**Comment by poojaranjan** [comment]
tx completed.
