### ISSUE TITLE
EIP Bot

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#165]
PR: https://github.com/ethereum/EIPs/pull/3351
![img](https://i.imgur.com/hFbhT1a.png)

Requesting amount in DAI = 7000 DAI @ $1.00 / DAI 
^ [Discussion of amount](https://youtu.be/jw42hSJC2e4?t=1490) (just for documentation)
Address = 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by alita-moore** [comment]
The bot is still sort of in progress, and I intend on continuing service on it while we get it integrated / built out. The process of debugging / getting setup with Github is in my mind included in this fee. But the base process of getting the bot written / fundamentally functional is done.

**Comment by poojaranjan** [comment]
Let's wait for Micah/Lightclients and/or @Souptacular confirmation to release this fund.

**Comment by Souptacular** [comment]
Funds can go out. We are super close to the bot being installed so it's basically done.

**Comment by poojaranjan** [comment]
created multisig tx 83 for #165 & #168
