### ISSUE TITLE
ETH 2.0 Call 59

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#166]
PR: https://github.com/ethereum/eth2.0-pm/pull/209

ETH Value
![eth value](https://i.imgur.com/QnMvWb4.png)

Amount: 0.00056*150 =0.0840 ETH
Address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
multisig tx 76 created, waiting for more approvals.

**Comment by poojaranjan** [comment]
Tx completed
