### ISSUE TITLE
EIPIP Meeting 29

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#168]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/63
<img width="999" alt="Screen Shot 2021-03-31 at 1 15 17 AM" src="https://user-images.githubusercontent.com/26529820/113098795-908e7100-91be-11eb-8c0b-aa6aa578ffbf.png">

amount: 100 DAI
address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
created multisig tx 83 for #165 & #168

**Comment by poojaranjan** [comment]
Payment success
