### ISSUE TITLE
Funding for notes - Eth2 Implementers Call #60

### ISSUE THREAD

**Issue by pedrorivera** [ethereum-cat-herders/funding#169]
PR: [eth2.0-pm/pull/211](https://github.com/ethereum/eth2.0-pm/pull/211)
Payable to: 0x686d0B9D00cE38533F6Fb009CaB058757f37A904
Amount: $150 in DAI

**Comment by poojaranjan** [comment]
Created multisig tx 82

**Comment by poojaranjan** [comment]
Transaction successful
