### ISSUE TITLE
Funding for note-taking for Ethereum Cat Herders call #15

### ISSUE THREAD

**Issue by DBrettRobertson** [ethereum-cat-herders/funding#17]
@CanonizerJim can you please provide your address so that the Ethereum Cat Herders can pay you for the [ECH Meeting #15 notes](https://github.com/ethereum-cat-herders/PM/blob/master/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%2015.md)?

**Comment by CanonizerJim** [comment]
Sure. 

0xED4aD2e886C5c31D298d1de49256C40239180D16

**Comment by CPSTL** [comment]
Approved: https://etherscan.io/tx/0xb2f758e8faa61b5d1d4f9e4c3d154e6325dd77175cb8ea2e82615672408d80de

**Comment by lrettig** [comment]
Updated spreadsheet, confirmed everything looks good, closing!

https://docs.google.com/spreadsheets/d/1PMCKHrkD2oGNXnDi6chy9DOFbpXgDRqpNz75PXSzoj4/edit#gid=0
