### ISSUE TITLE
ETH2.0 call#61

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#175]
- PR. : [ETH 2.0 call 61](https://github.com/ethereum/eth2.0-pm/pull/213)

![image](https://user-images.githubusercontent.com/74140118/114605813-1844a700-9cb8-11eb-90ef-6bf54769091c.png)

- Amount: 150/2282.87 =0.0657 ETH

- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Multisig tx 79 created for #175 & #173

**Comment by poojaranjan** [comment]
Transaction completed.
