### ISSUE TITLE
Funding for ECH #56

### ISSUE THREAD

**Issue by shanelightowler** [ethereum-cat-herders/funding#176]
PR: https://github.com/ethereum-cat-herders/PM/pull/171
Payable to: 0x6030f4C1657b61dD2db605be4510E79F9bE141bb
Amount: $100 in DAI

**Comment by poojaranjan** [comment]
Funds for documenting ECH meeting is 50 DAI

**Comment by poojaranjan** [comment]
Creating tx 86 (350 DAI) for #176 #177 #179

**Comment by poojaranjan** [comment]
Transaction completed!
