### ISSUE TITLE
Funding for EIPIP, #31

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#178]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/66
- Payable to `edson.eth`
- For amount $100 USD in ETH (0.036 ETH)

<img width="861" alt="Screen Shot 2021-04-29 at 8 17 41 PM" src="https://user-images.githubusercontent.com/34966228/116633622-a1e2ae80-a91f-11eb-8c7e-21de135dcaaa.png">

**Comment by poojaranjan** [comment]
multisig id 87 created

**Comment by edsonayllon** [comment]
Got it! Feel free to close
