### ISSUE TITLE
Funding for note-taking for Ethereum Cat Herders call #17

### ISSUE THREAD

**Issue by DBrettRobertson** [ethereum-cat-herders/funding#18]
Funding required for Ethereum Cat Herders [Meeting # 17 Notes](https://github.com/ethereum-cat-herders/PM/blob/master/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%2017.md).

**Comment by DBrettRobertson** [comment]
Funds to be sent to DBrettRobertson.gitcoin.eth

**Comment by lrettig** [comment]
Confirmed, spreadsheet updated, closing: https://etherscan.io/tx/0x1035719b8872a332a19e6cf6b0c2728ffb9bbae52ea59fe54590860fced5bfaa
