### ISSUE TITLE
Funding for  ETH2.0 call  #62

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#180]
- PR. : [ETH 2.0 call #62](https://github.com/ethereum/eth2.0-pm/pull/216)

![image](https://user-images.githubusercontent.com/74140118/116830419-6964fe00-abc7-11eb-8d25-220462384991.png)

![image](https://user-images.githubusercontent.com/74140118/116830437-931e2500-abc7-11eb-9688-aaed9a6d9195.png)

- Amount: 150/2681.01 =0.0559 ETH

- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Created multisig tx 85 (0.0727 ETH) for #180 & #181
