### ISSUE TITLE
Funding for ECH meeting #57

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#181]
- PR. : [ECH meeting 57](https://github.com/ethereum-cat-herders/PM/pull/174)

![image](https://user-images.githubusercontent.com/74140118/116830520-6fa7aa00-abc8-11eb-9cf0-0d4a33959272.png)

![image](https://user-images.githubusercontent.com/74140118/116830566-c9a86f80-abc8-11eb-9aed-b8d4bc399a0d.png)

- Amount: 50/2974.37 =0.0168 ETH

- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Created multisig tx 85 (0.0727 ETH) for #180 & #181

**Comment by poojaranjan** [comment]
Transaction completed!
