### ISSUE TITLE
Funding for EIPIP notes 32

### ISSUE THREAD

**Issue by shanelightowler** [ethereum-cat-herders/funding#184]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/68
Wallet: 0x6030f4C1657b61dD2db605be4510E79F9bE141bb
Value: 100 USD in ETH: 0.025 ETH

<img width="910" alt="Screenshot 2021-05-10 at 16 10 37" src="https://user-images.githubusercontent.com/60440347/117681887-762ab880-b1aa-11eb-9ef3-754fbfc258cc.png">

**Comment by poojaranjan** [comment]
Created multisig tx, waiting on approval.

**Comment by poojaranjan** [comment]
Transaction completed, please confirm and close the issue.

**Comment by Santhosh1692** [comment]
@shanelightowler Follow-up: If you have received the funds. Please do close the issue. cc @poojaranjan
