### ISSUE TITLE
Funding for ACD #110

### ISSUE THREAD

**Issue by jkcahill** [ethereum-cat-herders/funding#185]
[PR](https://github.com/ethereum/pm/pull/317)
Payable to: 0xa929F0764Ff83E4B815Ad0358927297Df9cD1e16
Amount: $150 in DAI

**Comment by poojaranjan** [comment]
Created multisig tx, waiting on approval.

**Comment by poojaranjan** [comment]
Transaction completed, please confirm and close the issue.
