### ISSUE TITLE
Funding for ETH2.0 Call #063

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#186]
- PR. : [ETH 2.0 call #63](https://github.com/ethereum/eth2.0-pm/pull/216)
 
![image](https://user-images.githubusercontent.com/74140118/118554314-ecb55080-b77e-11eb-9804-0260bb0ac219.png)
![image](https://user-images.githubusercontent.com/74140118/118555164-fa1f0a80-b77f-11eb-87f9-fc71502b423d.png)

- Amount: 150/3389.9 =0.0442 ETH
- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
created multisig tx, waiting for approval.

**Comment by poojaranjan** [comment]
Transaction completed, please confirm and close the issue.

**Comment by Santhosh1692** [comment]
@Avishek041180 Follow-up: If you have received the funds. Please do close the issue. cc @poojaranjan
