### ISSUE TITLE
Funding for Merge Implementers Call 04 notes 

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#187]
PR: [Merge Implementers Call 04 notes](https://github.com/ethereum/pm/pull/322)

Wallet: 0xEcebC7c42E3D16f70964d7d350FdFaE51ca5b5f6

Amount: 150 DAI

**Comment by poojaranjan** [comment]
Created multisig for #188 #187

**Comment by poojaranjan** [comment]
Transaction completed, please confirm and close the issue.

**Comment by Santhosh1692** [comment]
I have received it. Closing the thread.
