### ISSUE TITLE
Funding for Merge Implementers' Call #2 Notes

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#188]
PR: [Merge Implementers Call 02 notes](https://github.com/ethereum/pm/pull/325/files)

Wallet: 0xEcebC7c42E3D16f70964d7d350FdFaE51ca5b5f6

Amount: 150 DAI

**Comment by poojaranjan** [comment]
Created multisig for #188 #187

**Comment by poojaranjan** [comment]
Transaction completed, please confirm and close the issue.

**Comment by Santhosh1692** [comment]
I have received it. Closing the thread.
