### ISSUE TITLE
funding for notes, ech 59

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#189]
PR: https://github.com/ethereum-cat-herders/PM/pull/181
- Payable to `edson.eth`
- For $50 in ETH, or 0.019 ETH
<img width="1401" alt="Screen Shot 2021-05-31 at 10 34 03 PM" src="https://user-images.githubusercontent.com/34966228/120258591-f4cdbf80-c257-11eb-8656-a6006a6064d7.png">

**Comment by poojaranjan** [comment]
Created multisig tx, waiting on approval.

**Comment by poojaranjan** [comment]
transaction completed, please confirm & close

**Comment by edsonayllon** [comment]
Got it. https://etherscan.io/tx/0x7b1f681fb34cc1f36f68b2217d7c4e2a4e8330b9f150276fa0eb0ba6f8008420
