### ISSUE TITLE
Funding for note-taking for core devs call #68

### ISSUE THREAD

**Issue by DBrettRobertson** [ethereum-cat-herders/funding#19]
Funding required for All Core Devs Call [#68](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2068.md).

**Comment by DBrettRobertson** [comment]
Funds to be sent to DBrettRobertson.gitcoin.eth

**Comment by CPSTL** [comment]
I've confirmed this transaction. Reference: https://etherscan.io/tx/0x70f1500edbb470a0dad08fc6506495729feca3937097ade654bc4288cc89c64e

**Comment by lrettig** [comment]
Updated spreadsheet, confirmed everything looks good, closing!

https://docs.google.com/spreadsheets/d/1PMCKHrkD2oGNXnDi6chy9DOFbpXgDRqpNz75PXSzoj4/edit#gid=0
