### ISSUE TITLE
Funding for documenting Ethereum 2.0 Implementers Call 64 (notes)

### ISSUE THREAD

**Issue by DockBoss** [ethereum-cat-herders/funding#190]
[PR: Create call_064.md Review First #219 ](https://github.com/ethereum/eth2.0-pm/pull/219)

Ammount: 150 DAI

Address: jareddoro.eth

**Comment by poojaranjan** [comment]
General recommendation  - Please add a link of the PR and meeting name with number in the Issue header for quick reference. thanks!

**Comment by poojaranjan** [comment]
transaction completed, plz confirm and close the issue.

**Comment by poojaranjan** [comment]
Transaction completed, please confirm and close the issue.

**Comment by DockBoss** [comment]
Confirmed
