### ISSUE TITLE
Funding for ACD 112

### ISSUE THREAD

**Issue by dschirmerii** [ethereum-cat-herders/funding#193]
PR
Payable to: 0xc1aaF0F5236d632442aC86C01960CA72220Fbd22
Amount: $150 in DAI

**Comment by dschirmerii** [comment]
I apologize for opening this late, I completely forgot to do it.

**Comment by poojaranjan** [comment]
No worries. Created multisig tx for #193 #194.
Waiting for another approval.

**Comment by poojaranjan** [comment]
Transaction completed, please confirm and close the issue.

**Comment by dschirmerii** [comment]
Received thank you!
