### ISSUE TITLE
Funding for eth 2.0 call 65 Notes

### ISSUE THREAD

**Issue by jkcahill** [ethereum-cat-herders/funding#196]
PR - https://github.com/ethereum/eth2.0-pm/pull/221
Payable to: 0xa929F0764Ff83E4B815Ad0358927297Df9cD1e16
Amount: $150 in DAI

**Comment by poojaranjan** [comment]
multisig tx 100 created, waiting on approval.

**Comment by poojaranjan** [comment]
Transaction completed!
