### ISSUE TITLE
Funding for Merge 05 call notes

### ISSUE THREAD

**Issue by shanelightowler** [ethereum-cat-herders/funding#197]
PR: https://github.com/ethereum/pm/pull/335 
Wallet address: 0x6030f4C1657b61dD2db605be4510E79F9bE141bb
Amount requested: 150 DAI

**Comment by poojaranjan** [comment]
multisig tx 97 initiated, waiting on approval.

**Comment by poojaranjan** [comment]
Transaction completed!
