### ISSUE TITLE
Funding for EIP-1559 Gas API Call (Breakout #10)

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#198]
PR: [Notes to Meeting 10.md](https://github.com/ethereum/pm/pull/336)
Ether Wallet address: 0xEcebC7c42E3D16f70964d7d350FdFaE51ca5b5f6
Amount requested: 0.040 Ether

<img width="739" alt="Screenshot 2021-06-11 at 7 18 20 PM" src="https://user-images.githubusercontent.com/27824858/121698391-958b6d00-caeb-11eb-8150-37b1d350df51.png">

**Comment by poojaranjan** [comment]
multisig tx 99  created, waiting on approval.

**Comment by poojaranjan** [comment]
Transaction completed!
