### ISSUE TITLE
 Funding for Readme Update

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#199]
- PR : [Readme Update](https://github.com/ethereum/pm/pull/338)
- Amount: 250 USDC
- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
multisig tx 98 initiated for #195 & #199, waiting on approval.

**Comment by poojaranjan** [comment]
Transaction completed!
