### ISSUE TITLE
Proposal: provide initial funds to Ethereum Cat Herders DAO

### ISSUE THREAD

**Issue by chrishobcroft** [ethereum-cat-herders/funding#2]
This is a proposal to provide a nominal sum of e.g. 50 DAI to the "Finance" app of the Aragon DAO.

This will allow proposals to be made for withdrawals from this app, to fund Ethereum Cat Herder activities.

The address for this Finance app is 0x4eF0A899BF3e8065602Acf86D4f169D111C2D44f

This can be verified at this link: https://mainnet.aragon.org/#/ethereumcatherders.aragonid.eth/settings

![Screenshot from 2019-03-10 22-24-33](https://user-images.githubusercontent.com/2212651/54092389-58bbf300-4383-11e9-82da-edfc574b9c74.png)

**Comment by lrettig** [comment]
We currently hold around $583 equivalent, mostly in DAI. I'm okay with this as an experiment. Anyone opposed?

@chrishobcroft should this be done using DAI?

**Comment by chrishobcroft** [comment]
Confirmed that the DAO can receive DAI:

![Screenshot from 2019-03-13 13-44-00](https://user-images.githubusercontent.com/2212651/54283520-1fa79c80-4596-11e9-8715-d8de25916440.png)

@lrettig yes, I would send this using DAI. Recommend using the "New transfer" function on the [DAO's Finance App](https://mainnet.aragon.org/#/ethereumcatherders.aragonid.eth/0x4ef0a899bf3e8065602acf86d4f169d111c2d44f), which integrates with MetaMask nicely.

**Comment by chrishobcroft** [comment]
The address for receiving funds into this DAO is here: 0x4eF0A899BF3e8065602Acf86D4f169D111C2D44f

@lrettig what more do we need to do to provide some funding to this? It would provide full transparency of all expenditure, and furthermore would devolve out the responsibility of funding costs.

**Comment by lrettig** [comment]
Hi Chris, just to be explicit, I can just make an ordinary dai transfer to
this address? Nothing else whatsoever needs to be done?

**Comment by chrishobcroft** [comment]
Yes, that's right - for example, I sent 0.1 DAI to that address in [this transaction](https://etherscan.io/tx/0x981b2f76896291d11b57ec9f93ebf8460dd28cbe7a4ca0560c61bcdbee9513aa) and it's now showing in the "Token Balance" within [the ethcatherder's DAO's "Finance" App](https://mainnet.aragon.org/#/ethereumcatherders.aragonid.eth/0x4ef0a899bf3e8065602acf86d4f169d111c2d44f). This txn did cost a little more in gas, due to the nature of the contract that was receiving it.

Once there are funds in the DAO's Finance App, then anyone can propose a withdrawal, which would need to be voted upon by the DAO before it would automatically be transferred (autonomously).

**Comment by lrettig** [comment]
Done: https://etherscan.io/tx/0x9078c3abda4f71a480b369848d85b13887d8741c981563bfd94007cf3b3769d1

**Comment by chrishobcroft** [comment]
OK, my bad - that was the wrong thing to advise you to do. I'm sorry.

It's apparently only OK to send Ether to that address - not non-ETH tokens - see warning in bottom right.

![Screenshot from 2019-03-19 23-43-02](https://user-images.githubusercontent.com/2212651/54649524-79cac500-4aa2-11e9-9814-332e4c7c5e13.png)

So, now it looks like the DAI is stuck in that contract.

I have made amends by transferring 50 DAI from my own pocket.

Apologies for the error.

**Comment by chrishobcroft** [comment]
For future reference, the right way to do this is to create a "New transfer" from [the DAO's Finance App page](https://mainnet.aragon.org/#/ethereumcatherders.aragonid.eth/0x4ef0a899bf3e8065602acf86d4f169d111c2d44f).

First, click "New transfer" button in the top right:

![Screenshot from 2019-03-20 00-01-11](https://user-images.githubusercontent.com/2212651/54649748-5f451b80-4aa3-11e9-9a5f-3522789b5e1f.png)

then, select the token you would like to Deposit, and the amount, adding an option reference:

![Screenshot from 2019-03-20 00-01-20](https://user-images.githubusercontent.com/2212651/54649755-666c2980-4aa3-11e9-9653-a23534a44280.png)

Then it will prompt you to submit 2 transactions (an approve, then a deposit).

![Screenshot from 2019-03-20 00-03-59](https://user-images.githubusercontent.com/2212651/54649833-b3500000-4aa3-11e9-8715-153f8c1870ba.png)

**Comment by lrettig** [comment]
Yikes. Okay. Lesson learned. Shall we ask the Aragon folks if there's nothing that can be done to fix this?

**Comment by chrishobcroft** [comment]
I have asked in Aragon's Rocket Chat. I will report back if I get a response.

![Screenshot from 2019-03-20 00-29-43](https://user-images.githubusercontent.com/2212651/54650615-522a2b80-4aa7-11e9-981f-e6fa57928727.png)

**Comment by chrishobcroft** [comment]
@lrettig further to collaboration with Aragon, these funds have been recovered into the DAO, via this transaction:

https://etherscan.io/tx/0x171d0e368952e7236ce9560d90178d06a668c84d1897b16b82bc7dac412c5fd0

Big thanks to @0xGabi from Aragon Community for helping.

The solution involved:

1. [Installing aragonCLI](https://hack.aragon.org/docs/cli-intro.html) which is a CLI for interacting with Aragon DAOs

2. Running `aragon ipfs` in Terminal - in order to provide aragonCLI with a way to access data (e.g. ABIs) for Aragon DAOs

3. [Setting a Private Key for aragonCLI to use](https://hack.aragon.org/docs/guides-faq#set-a-private-key), and supplying some Ether to the address for this key, to pay for gas.

4. Sending the following transaction from aragonCLI:

```
dao exec 0x8bfeae877a065301fbd692b38a94639ffecae90e 0x4ef0a899bf3e8065602acf86d4f169d111c2d44f recoverToVault 0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359 --environment aragon:mainnet
```

**Comment by chrishobcroft** [comment]
In order to close this out, I have proposed a vote for the **extra** 50 DAI that I supplied from my own pocket to be sent back to me.

If any HERD token holders disagree with this, you can vote against this motion at the following link.

https://mainnet.aragon.org/#/ethereumcatherders.aragonid.eth/0xe837d5bacfddf6fd0fab88fa314681d7926c7399

The vote expires on 2019-03-27 at 1419.

**Comment by lrettig** [comment]
Vote passed, tx executed (https://etherscan.io/tx/0x55003323a8939e70928a75775da6f72cbe22108a9495a66863fd6f3160e7f08b), closing
