### ISSUE TITLE
Funding for ACD 115

### ISSUE THREAD

**Issue by shanelightowler** [ethereum-cat-herders/funding#200]
PR: https://github.com/ethereum/pm/pull/339
Wallet: 0x6030f4C1657b61dD2db605be4510E79F9bE141bb
Amount requested: 0.057 ETH

<img width="1412" alt="Screenshot 2021-06-15 at 09 01 54" src="https://user-images.githubusercontent.com/60440347/122015950-7ecd6a80-cdb8-11eb-8cc7-dcaac25eecfd.png">

**Comment by poojaranjan** [comment]
multisig tx 96 initiated, waiting on approval.

**Comment by poojaranjan** [comment]
Transaction completed!
