### ISSUE TITLE
Funding for ACD 113

### ISSUE THREAD

**Issue by KenMan79** [ethereum-cat-herders/funding#201]
PR: ethereum/pm#327
Wallet: 0x25beCA2CA35dB9d46cCaB9e62F85f100BF0E8078
Amount requested: 0.057 ETH

**Comment by poojaranjan** [comment]
@KenMan79 if you need this fund in ETH, could you please add the screenshot of the price of Ether on the day when the notes were submitted? 
Ref. : https://github.com/ethereum-cat-herders/funding/issues/180

**Comment by KenMan79** [comment]
Understand

**Comment by KenMan79** [comment]
May 14th 2021 price of ETH 
<img width="575" alt="May14h2021" src="https://user-images.githubusercontent.com/51566205/123030217-0e21e180-d3a8-11eb-9a16-0d354bee6f76.png">

**Comment by KenMan79** [comment]
PR: ethereum/pm#327
Wallet: 0x25beCA2CA35dB9d46cCaB9e62F85f100BF0E8078
Amount requested: 150.00 DAI
<img width="802" alt="May 14h 2021 ACD Meeting PR: ethereum:pm#327" src="https://user-images.githubusercontent.com/51566205/123035144-7248a380-d3b0-11eb-9e16-af2bc7b84931.png">
DAI

**Comment by poojaranjan** [comment]
Created multisig transaction 101, waiting on approval.

**Comment by poojaranjan** [comment]
Transaction completed!
