### ISSUE TITLE
funding for ETH2 call 66

### ISSUE THREAD

**Issue by dschirmerii** [ethereum-cat-herders/funding#206]
PR :Merge Meeting #[66](https://github.com/ethereum/eth2.0-pm/pull/223)
Amount: 150 DAI
Wallet: 0xc1aaF0F5236d632442aC86C01960CA72220Fbd22

**Comment by poojaranjan** [comment]
Initiated tx 109 for #206 #208. Waiting on approval & execution

**Comment by poojaranjan** [comment]
The transaction is successful!
