### ISSUE TITLE
ECH Engineering Funding June 2021

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#207]
You can see the work completed this month here: https://github.com/ethereum-cat-herders/PM/issues/208

Amount: 40 hours * 50$ / hr = 2000$ = 2000 DAI
Address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Initiated tx 110. Waiting on approval & execution.

**Comment by poojaranjan** [comment]
The transaction is successful!
