### ISSUE TITLE
Funding for EIPIP 36 notes

### ISSUE THREAD

**Issue by dschirmerii** [ethereum-cat-herders/funding#208]
PR :EIPIP [36](https://github.com/ethereum-cat-herders/EIPIP/pull/77)
Amount: 150 DAI
Wallet: 0xc1aaF0F5236d632442aC86C01960CA72220Fbd22

**Comment by poojaranjan** [comment]
Bounty for EIPIP meeting is 100 DAI

**Comment by poojaranjan** [comment]
Initiated tx 109 for #206 #208. Waiting on approval & execution

**Comment by dschirmerii** [comment]
My apologies I didn't realize.

**Comment by poojaranjan** [comment]
No problem.
The transaction is successful!
