### ISSUE TITLE
Funding for ACD 116

### ISSUE THREAD

**Issue by golden-gringo** [ethereum-cat-herders/funding#209]
[PR](https://github.com/ethereum/pm/pull/346)
Wallet: 0xb3884d43Eba3f2f7585F3a23f854C150Ac31b0e5
Amount Requested: 150 DAI

**Comment by poojaranjan** [comment]
Initiated multisig tx 111, waiting on one more approval & execution.

**Comment by poojaranjan** [comment]
The transaction is successful!
