### ISSUE TITLE
Funding for note-taking for core devs call #70

### ISSUE THREAD

**Issue by DBrettRobertson** [ethereum-cat-herders/funding#21]
Please send funds to dbrettrobertson.gitcoin.eth

**Comment by lrettig** [comment]
Updated spreadsheet, confirmed everything looks good, closing!

https://docs.google.com/spreadsheets/d/1PMCKHrkD2oGNXnDi6chy9DOFbpXgDRqpNz75PXSzoj4/edit#gid=0
