### ISSUE TITLE
Funding for EIP editor, June 2021

### ISSUE THREAD

**Issue by lightclient** [ethereum-cat-herders/funding#212]
Hours: 25

Amount: 1625 USDC

Wallet: `ordinary.eth`

Thank you!

**Comment by poojaranjan** [comment]
25 hrs @ 65 USDC/DAI per hour = 1625 USDC

**Comment by poojaranjan** [comment]
Initiated multisig tx 114, waiting on one more approval & execution.

**Comment by poojaranjan** [comment]
The transaction is successful!
