### ISSUE TITLE
Funding for Eth2 Call 67 

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#213]
PR: https://github.com/ethereum/eth2.0-pm/pull/225
Amount: 150 DAI
Wallet: 0xEcebC7c42E3D16f70964d7d350FdFaE51ca5b5f6

**Comment by poojaranjan** [comment]
Initiated mutisig tx 108 for #205 & #213. Waiting on approval & execution.

**Comment by poojaranjan** [comment]
The transaction is successful!
