### ISSUE TITLE
Funding for ECH Ops, June 2021

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#216]
Hours: 18.5

Amount 18.5 (hrs) * 50 USDC = 925 USDC / DAI

Amount: 925 DAI
Wallet: 0xEcebC7c42E3D16f70964d7d350FdFaE51ca5b5f6

**Comment by poojaranjan** [comment]
multisig tx 120 created, wait for one more confirmation.

**Comment by poojaranjan** [comment]
tx completed
