### ISSUE TITLE
Funding for ECH Meeting 20 Notes.

### ISSUE THREAD

**Issue by DBrettRobertson** [ethereum-cat-herders/funding#22]
Please arrange funding for ECH Meeting 20 [Notes](https://github.com/ethereum-cat-herders/PM/blob/master/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%2020.md).

Funds can be sent to dbrettrobertson.gitcoin.eth

**Comment by lrettig** [comment]
Amount?

**Comment by lrettig** [comment]
Submitted tx to multisig to send 50 DAI (SAI? whatever it's called now) to 0x233c630be34d97e4eacf6d6450389d9ce1294d0d.

@DBrettRobertson please double-check that the recipient address is correct.

@CPSTL @Souptacular @timbeiko if all looks good and Brett confirms, please confirm the tx. Thanks!

Ref: https://etherscan.io/tx/0x5213825b6b3987657af0b337c8d0d0c02ba765567de369a2dd13741b3c471d45

**Comment by timbeiko** [comment]
Confirmed! You should have received the funds at the specified address. Thank you for your patience 😄 !
