### ISSUE TITLE
Funding for Eth2.0 meeting 68

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#220]
PR:Eth2.0 meeting 68
Amount: 150 USDC
Wallet: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
Please add the link to the Pull Request.

**Comment by darkfire-rain** [comment]
ethereum/eth2.0-pm#228
Here you go!

**Comment by poojaranjan** [comment]
multisig tx 117 created, pls. wait for one more confirmation.

**Comment by poojaranjan** [comment]
tx completed
