### ISSUE TITLE
Funding for EIP IP Meeting # 35

### ISSUE THREAD

**Issue by Prutha2** [ethereum-cat-herders/funding#222]
Meeting Date: Wednesday June 16, 2021
Pull Request Date: Friday June 25, 2021

PR: [Add notes for meeting # 35](https://github.com/ethereum-cat-herders/EIPIP/pull/76)
Amount: 0.055151 Eth = 100 / 1,813.22 (see [Yahoo Finance](https://finance.yahoo.com/quote/ETH-USD/history?period1=1624579200&period2=1624579200&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true) for a value on Friday June 25, 2021.)
Payable to canonizer.eth

**Comment by poojaranjan** [comment]
multisig tx 126. Need one more approval.

**Comment by poojaranjan** [comment]
tx completed!
