### ISSUE TITLE
Funding for Catblazer, July '21

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#224]
Hours: 20

Amount: 0.38450447 ETH

Wallet: `wschwab.eth`

Proof of Price:

20 (hrs) * 50 USD = 1000 USD, price of ETH: 2600.75 USD (screenshot attached), 1000/2600.75 = 0.38450447 ETH

![eth_price_jul_2021](https://user-images.githubusercontent.com/31592931/127781986-ced73205-1a25-46b0-8e10-46a2f0ab383a.png)

Thanks!

**Comment by poojaranjan** [comment]
multisig tx 124. Need one more approval.

**Comment by poojaranjan** [comment]
tx completed!
