### ISSUE TITLE
Funding for EIPIP meeting #33

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#225]
PR: [EIPIP meeting 33](https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20033.md) 
Amount: 100 USDC/DAI
Wallet: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
Please add your wallet address

**Comment by poojaranjan** [comment]
multisig tx 128. Need one more approval.

**Comment by poojaranjan** [comment]
tx completed!
