### ISSUE TITLE
Funding for EIPIP meeting 038

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#228]
- PR :[EIPIP Meeting 038](https://github.com/ethereum-cat-herders/EIPIP/pull/81)
- Amount: 100 USDC
- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Created tx 129, waiting for another confirmation.

**Comment by poojaranjan** [comment]
tx successful!
