### ISSUE TITLE
Reimbursement for London NFT Gas costs

### ISSUE THREAD

**Issue by Wyxuan1** [ethereum-cat-herders/funding#231]
20 dollars - Gas minting cost
10 dollars - cost of gas to send NFTs to William Schwab.

**Comment by Wyxuan1** [comment]
Address is Williamx.eth and you can verify using etherscan

**Comment by poojaranjan** [comment]
@Wyxuan1 Is it possible to have Etheracan links for the transactions?

Also, let us know the preferred token  - DAI/USDC/ETH?

**Comment by poojaranjan** [comment]
Sorry, I missed it earlier. the gas cost will be refunded in ETH.

**Comment by poojaranjan** [comment]
@Wyxuan1 
friendly reminder, please add the Etherscan link for reference

**Comment by Wyxuan1** [comment]
Here is the mint tx https://etherscan.io/tx/0x7ace020cedfbd74a8d08fa721ed92bcf8fb75c152a9783222812e003317c2f2c <https://etherscan.io/tx/0x7ace020cedfbd74a8d08fa721ed92bcf8fb75c152a9783222812e003317c2f2c>
Here is the tx that I used to send the NFTs to William Schwab: https://etherscan.io/tx/0x06de72eb51261393a5dfab9d4c54b914fddb025071bfb9954884ba5d8ea940c5

**Comment by poojaranjan** [comment]
Mint tx: 0.007346472 ETH
send the NFTs to William Schwab: 0.0024403236 ETH 

Total funds = 0.0097867956 ETH

Multisig tx 135 created, waiting on another signature for execution.

**Comment by poojaranjan** [comment]
tx. completed!
