### ISSUE TITLE
ECH Engineering July 2021

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#232]
You can see the work completed this month here: https://github.com/ethereum-cat-herders/PM/issues/211

Amount: 40 hours * 50$ / hr = 2000$ = 2000 DAI
Address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Multisig tx 132 created. Waiting on another confirmation.

**Comment by poojaranjan** [comment]
tx successful!
