### ISSUE TITLE
Funding for ECH Meeting # 64 #223

### ISSUE THREAD

**Issue by KinnShah** [ethereum-cat-herders/funding#233]
Date Sunday August 8, 2021

PR: ethereum-cat-herders/PM#223
Amount: 0.016591 Eth = 50 / 3013.73 (see [yahoo finance](https://finance.yahoo.com/quote/ETH-USD/history?period1=1628380800&period2=1628380800&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true) for ether high on that day.)
Payable To: canonizer.eth

**Comment by poojaranjan** [comment]
Multisig tx. 133 created, waiting on another confirmation.

**Comment by poojaranjan** [comment]
tx successful!
