### ISSUE TITLE
Funding for eth2.0 implementer #70

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#234]
PR: https://github.com/ethereum/eth2.0-pm/pull/228
Amount: 150 DAI/USDC
Wallet address: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
Created multisig tx 134, waiting on another confirmation.

**Comment by poojaranjan** [comment]
tx. completed!
