### ISSUE TITLE
Funding for EIP IP Meeting # 39

### ISSUE THREAD

**Issue by KinnShah** [ethereum-cat-herders/funding#235]
Meeting Date: Tuesday August 17, 2021
Pull Request Date: Tuesday August 17, 2021

PR: Add notes for meeting # 39
Amount: 0.033169 Eth = 100 /3014.85 (see [Yahoo Finance](https://finance.yahoo.com/quote/ETH-USD/history?period1=1629158400&period2=1629158400&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true) for a value on Tuesday August 17, 2021.)
Payable to canonizer.eth

**Comment by poojaranjan** [comment]
Multisig tx 136 created, waiting on another signature.

**Comment by poojaranjan** [comment]
tx. completed!
