### ISSUE TITLE
Funding for EIPIP meeting 40

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#238]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/86
Amount: 100 DAI/USDC
Wallet address: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
Initiated tx 142, need another confirmation.

**Comment by poojaranjan** [comment]
Tx completed.
