### ISSUE TITLE
Funding for ECH Meeting 21 Notes

### ISSUE THREAD

**Issue by thesachinmittal** [ethereum-cat-herders/funding#24]
Please arrange funding for ECH Meeting 21 [Notes](https://github.com/ethereum-cat-herders/PM/pull/98)

Funds can be sent [here](https://gitcoin.co/thesachinmittal).

**Comment by lrettig** [comment]
Submitted tx to multisig to send 50 DAI (SAI? whatever it's called now) to 0xc5d6d2ea25bb7cf7c997ba135fdd141555884685.

@thesachinmittal please double-check that the recipient address is correct. (I got it from your gitcoin account.)

@CPSTL @Souptacular @timbeiko if all looks good and OP confirms the address, please confirm the tx. Thanks!

Ref: https://etherscan.io/tx/0xbb1dbff45b934c2517787a50a417c7f21b406fcbdd34c2fca54403829acfec96

**Comment by thesachinmittal** [comment]
Thanks @lrettig! Address is correct guys.

**Comment by timbeiko** [comment]
Confirmed! You should have received the funds at the specified address. Thank you for your patience 😄 !
