### ISSUE TITLE
Funding for Catblazer, Aug '21

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#241]
Hours: 20

Amount: 0.279655353 ETH

Wallet: wschwab.eth

Proof of Price:

20 (hrs) * 50 USD = 1000 USD, price of ETH: 3575.83 USD (screenshot attached), 1000/2600.75 = 0.279655353 ETH

![eth_price_sep_1_21](https://user-images.githubusercontent.com/31592931/131704577-1cc0c80a-3c5c-4b79-a86a-e3eb6d3cf0a8.png)

Thanks!

**Comment by poojaranjan** [comment]
Initiated tx 140, need another confirmation.

**Comment by poojaranjan** [comment]
Tx completed.
