### ISSUE TITLE
Gas Refunds

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#242]
Refunds for London NFT gas and multisig txs:

Total: 0.211061119 ETH
Address: `wschwab.eth`

London NFT gas to date (after 59 transfers, Sep 2 2021): 0.1648275844
Multisig tx gas to date (txs 106-112, 122-128, 137): 0.046233535

**Comment by poojaranjan** [comment]
Initiated tx 140, need another confirmation.

**Comment by poojaranjan** [comment]
Tx completed.
