### ISSUE TITLE
Funding for  ETH2.0 call #71

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#243]
- PR. : [ETH2.0 call#71](https://github.com/ethereum/eth2.0-pm/pull/234)
- Amount: 150 DAI/USDC
- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
tx initiated for #240 #243. Need one more confirmation.

**Comment by poojaranjan** [comment]
Tx completed.
