### ISSUE TITLE
ECH Engineering August 2021

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#248]
You can see the work completed this month here: https://github.com/ethereum-cat-herders/PM/issues/224

Amount: 40 hours * 50$ / hr = 2000$ = 2000 DAI
Address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Multisig tx 145 initiated, need one more confirmation.

**Comment by poojaranjan** [comment]
Transaction executed. Thanks!
