### ISSUE TITLE
ACD-122 notes

### ISSUE THREAD

**Issue by minimalsm** [ethereum-cat-herders/funding#249]
PR: https://github.com/ethereum/pm/pull/393
Wallet: `0xd33f6E443D5277E7A0040672885358E22E1E7356`
Amount: 0.04462227246 ETH

<img width="234" alt="Screenshot 2021-09-20 at 21 55 38" src="https://user-images.githubusercontent.com/62268199/134074521-495642a6-4490-4053-869b-54ae874f2881.png">

<img width="281" alt="Screenshot 2021-09-20 at 21 54 30" src="https://user-images.githubusercontent.com/62268199/134074516-1f305290-de78-4ec7-bb35-39dc4adfe2ff.png">

<img width="1019" alt="Screenshot 2021-09-20 at 22 08 12" src="https://user-images.githubusercontent.com/62268199/134076023-abde37b6-8baf-4bee-87b7-88cb1617a4b8.png">

**Comment by poojaranjan** [comment]
Transaction executed. Thanks!
