### ISSUE TITLE
Funding for notes, Core Devs call #74

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#25]
[Call 74](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2074.md). Please send funds to `edsonayllon.eth`.

**Comment by lrettig** [comment]
Submitted tx to multisig to send 50 DAI (SAI? whatever it's called now) to 0xBBAac64b4E4499aa40DB238FaA8Ac00BAc50811B.

@edsonayllon please double-check that the recipient address is correct.

@CPSTL @Souptacular @timbeiko if all looks good and OP confirms the address, please confirm the tx. 48 in multisig. Thanks!

Ref: https://etherscan.io/tx/0x6b35baea224b2f1cd2bfdbb9d376a4a8a4d1e9998f5d5c1ff9bf6d7d2f250949

**Comment by edsonayllon** [comment]
@lrettig Yup, the address is correct.

**Comment by timbeiko** [comment]
Confirmed! You should have received the funds at the specified address. Thank you for your patience 😄 !
