### ISSUE TITLE
Funding for ECH meeting 67

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#250]
**PR**: https://github.com/ethereum-cat-herders/PM/pull/232

**Amount**: 0.0150466 ETH
![image](https://user-images.githubusercontent.com/67558925/135167048-a57b69e8-03b0-4ce5-a0b2-9cff498abc6c.png)
![image](https://user-images.githubusercontent.com/67558925/135167095-4d2e3e03-baa7-4946-9f20-584312e20628.png)

**Wallet address**: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
multisig transaction 148 created for #250 #251, need another confirmation

**Comment by poojaranjan** [comment]
Transaction executed. Thanks!
