### ISSUE TITLE
Funding for Merge meeting 9

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#251]
**PR**: https://github.com/ethereum/pm/pull/392

**Amount**: 
![image](https://user-images.githubusercontent.com/67558925/135168074-1f1219d9-6137-4034-baef-7def73572ecc.png)

![image](https://user-images.githubusercontent.com/67558925/135167824-4b69d857-766c-4135-9f9e-10ddf858e516.png)

**Wallet address**: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
multisig transaction 148 created for #250 #251, need another confirmation

**Comment by poojaranjan** [comment]
Transaction executed. Thanks!
