### ISSUE TITLE
Funding for ETH2.0 Call#73

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#252]
- PR : [ETH2.0 Call#73](https://github.com/ethereum/eth2.0-pm/pull/234)
![image](https://user-images.githubusercontent.com/74140118/135174190-a4621b9d-bb11-4427-8baa-1813b9f45a64.png)
![image](https://user-images.githubusercontent.com/74140118/135174304-87fe0640-8f9c-45db-be38-a36ad51b058a.png)

- Amount: 150/2870.3=0.0523 ETH
- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
multisig tx 149 created, need another confirmation.

**Comment by poojaranjan** [comment]
Transaction executed. Thanks!
