### ISSUE TITLE
Funding for EIPIP 41

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#253]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/88
- Payable to `edson.eth`
- For $100 in ETH, 0.034 ETH

<img width="1436" alt="Screen Shot 2021-09-29 at 2 45 33 AM" src="https://user-images.githubusercontent.com/34966228/135217037-70640acf-80f8-40c1-9aad-9ad52eefcd5b.png">

**Comment by poojaranjan** [comment]
Transaction executed. Thanks!
