### ISSUE TITLE
Funding for notes, ECH call #22

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#26]
[Call 22](https://github.com/ethereum-cat-herders/PM/blob/660efdcac6e7144a33adfc01c9ac46b1239496fc/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%2022.md). Please send funds to `edsonayllon.eth`.  Also, the PR still needs review and merge: [PR #97](https://github.com/ethereum-cat-herders/PM/pull/97).

**Comment by timbeiko** [comment]
@edsonayllon I put in the first multisig transaction to move 50 DAI to `0xBBAac64b4E4499aa40DB238FaA8Ac00BAc50811B`. Can you confirm the address? 

@lrettig @Souptacular @CPSTL

**Comment by edsonayllon** [comment]
@timbeiko Yes, the address is correct.

**Comment by edsonayllon** [comment]
Tx: `0x1741398fab9113b0b9213ba1c0213f04e1f6cbaad358d156e4f2d7ef0884f775`

**Comment by edsonayllon** [comment]
Sorry about that, reopening so it's added to the spreadsheet.

**Comment by CPSTL** [comment]
Confirmed.
