### ISSUE TITLE
Funding for ECH meeting 69 notes

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#260]
PR: https://github.com/ethereum-cat-herders/PM/pull/239
- Payable to `edson.eth`
- For amount $50, 0.01315 ETH.

<img width="847" alt="Screen Shot 2021-10-19 at 4 27 01 AM" src="https://user-images.githubusercontent.com/34966228/137874576-67e57696-b846-4c5a-89ae-70fc65680229.png">

**Comment by poojaranjan** [comment]
Multisig tx 156 initiated, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
