### ISSUE TITLE
Funding for EIPIP meeting 042

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#261]
- PR :  [EIPIP Meeting 042](https://github.com/ethereum-cat-herders/EIPIP/pull/89)

![image](https://user-images.githubusercontent.com/74140118/138964260-e082df54-cefe-443c-9277-4f0c4c2eef52.png)

![image](https://user-images.githubusercontent.com/74140118/139380828-714a7970-051b-46dd-a1cd-940a6455f0a9.png)

- Amount: 100/4271.21=0.0234 ETH

- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Multisig tx 157 initiated, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
