### ISSUE TITLE
Funding for ETH2.0 Implementers Call Notes

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/funding#262]
PR: https://github.com/ethereum/eth2.0-pm/pull/240

Amount: 0.0375 ETH (equivalent to $150 USD. ETH/USD at time of PR is $3998.41, thus 150 / 3998.41 = ~0.0375)

Wallet address: 0x2f51E78ff8aeC6A941C4CEeeb26B4A1f03737c50

<img width="1408" alt="Screen Shot 2021-10-27 at 2 18 46 PM" src="https://user-images.githubusercontent.com/54918343/139125435-7461a2b4-83ac-4c37-ac10-7f4eb8a8fbc6.png">

**Comment by poojaranjan** [comment]
multisig tx 158 initiated, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
