### ISSUE TITLE
ACD-124 notes

### ISSUE THREAD

**Issue by minimalsm** [ethereum-cat-herders/funding#263]
PR: https://github.com/ethereum/pm/pull/403
Wallet: `0xd33f6E443D5277E7A0040672885358E22E1E7356`
Amount: 0.03624055027 ETH

<img width="666" alt="Screenshot 2021-10-28 at 09 13 33" src="https://user-images.githubusercontent.com/62268199/139215273-28e93686-2483-4b5a-9a6f-107b7009ebf5.png">

<img width="988" alt="Screenshot 2021-10-28 at 09 11 37" src="https://user-images.githubusercontent.com/62268199/139215260-f8592d26-fd64-4503-8bc9-8a07dee89ffa.png">

**Comment by poojaranjan** [comment]
multisig tx 159 initiated, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
