### ISSUE TITLE
Funding for task "Move ETH 1.x & Fee Market folders to Archive"

### ISSUE THREAD

**Issue by stefan-wuest** [ethereum-cat-herders/funding#264]
PM: https://github.com/ethereum-cat-herders/PM/issues/240
Amount: 0.0230670929465443 ETH
Wallet: 0xeE13fCC1c4310f35a3A8817AD95FE7a9066EBCa3

![image](https://user-images.githubusercontent.com/20667579/139532875-6ec5112a-8e32-4932-b9de-2152fd0f6db5.png)

![image](https://user-images.githubusercontent.com/20667579/139532891-3cf16b77-52e6-48b9-b9f0-42ea4e54de4d.png)

**Comment by poojaranjan** [comment]
multisig tx 160 initiated. waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
