### ISSUE TITLE
ACD 125 notes

### ISSUE THREAD

**Issue by shanelightowler** [ethereum-cat-herders/funding#266]
Wallet: 0xE5a82f9360b9D105F82d264B35b09C7442c93BbF
PR: https://github.com/ethereum/pm/pull/411
Amount: 0.0332077343

![image](https://user-images.githubusercontent.com/60440347/139955094-bd4b7c54-9d0d-458a-81d1-85f0d9d571da.png)

<img width="1433" alt="Screenshot 2021-11-02 at 21 32 25" src="https://user-images.githubusercontent.com/60440347/139954888-5a814f2e-cf26-4e3f-b88c-a827c482f826.png">

**Comment by poojaranjan** [comment]
multisig tx 162 initiated, waiting for 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
