### ISSUE TITLE
Funding for Catblazer, Oct '21

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#269]
Hours: 20

Amount: 0.231705678 ETH

Wallet: `wschwab.eth`

On Price:
CoinGecko's price closest to 11:59PM Oct 31: $4315.82
1000 /4315.82 = 0.231705678

**Comment by poojaranjan** [comment]
created multisig tx 164, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
