### ISSUE TITLE
Funding for notes ECH Meeting #23

### ISSUE THREAD

**Issue by DBrettRobertson** [ethereum-cat-herders/funding#27]
For payment of 50 DAI to dbrettrobertson.gitcoin.eth

**Comment by timbeiko** [comment]
@DBrettRobertson I submitted the multisig txn to send 50 DAI to `0x233C630bE34D97e4eaCF6D6450389d9Ce1294D0d` can you please confirm the address?

@lrettig @Souptacular @CPSTL it's #51 in the multisig.

**Comment by DBrettRobertson** [comment]
0x233c630be34d97e4eacf6d6450389d9ce1294d0d is confirmed.

**Comment by CPSTL** [comment]
Confirmed ([tx](https://etherscan.io/tx/0x25178581f22bd177cf4b6fb2b8946e160004ec11d980a7e653acc452dfa32b51)) and added to spreadsheet.
