### ISSUE TITLE
EIPIP meeting 43 notes

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#273]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/92
Amount: 150 DAI
Wallet: 0xEcebC7c42E3D16f70964d7d350FdFaE51ca5b5f6

**Comment by poojaranjan** [comment]
I created the transaction (168) for 150 DAI but the bounty for the EIPIP meeting is 100 DAI. This can be adjusted in the next payment. 

A note for future reference
- ACD & Consensus meeting 150 DAI
- EIPIP meeting 100 DAI
- ECH meeting 50 DAI

Thanks for your contribution!

**Comment by Santhosh1692** [comment]
Noted. I apologise for the inconvenience. I'll remind about adjustment at the next meeting note.

**Comment by poojaranjan** [comment]
tx completed!
