### ISSUE TITLE
Funding for task "Documenting notes Merge Community meeting #1"

### ISSUE THREAD

**Issue by stefan-wuest** [ethereum-cat-herders/funding#274]
PM: ethereum-cat-herders/PM#246
Amount: 0.0211658129788765 ETH
Wallet:  0xeE13fCC1c4310f35a3A8817AD95FE7a9066EBCa3

![image](https://user-images.githubusercontent.com/20667579/141183331-740622df-503c-469e-9dde-f9196fc6b297.png)

![image](https://user-images.githubusercontent.com/20667579/141183526-72816e87-5030-4453-ba82-41b3a5a85692.png)

**Comment by poojaranjan** [comment]
Created multisig tx 169. Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
