### ISSUE TITLE
Funding for ACD meeting notes

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/funding#276]
PR: https://github.com/ethereum/pm/pull/420

Wallet: 0x2f51E78ff8aeC6A941C4CEeeb26B4A1f03737c50

Amount: 0.03582885 ETH (150/4186.57 = 0.035828852736249)

<img width="977" alt="Screen Shot 2021-11-18 at 7 56 24 AM" src="https://user-images.githubusercontent.com/54918343/142419886-b9eb296a-253d-463e-a863-554e93e75962.png">

**Comment by poojaranjan** [comment]
for ACD meeting 126
created multisig transaction 171, wai

**Comment by poojaranjan** [comment]
tx completed!
