### ISSUE TITLE
ECH Eng Nov 2021

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#277]
You can see the work completed this month here: 
https://github.com/ethereum-cat-herders/PM/issues/245#issue-1041834745

Amount: 40 hours * 50$ / hr = 2000$ = 2000 DAI
Address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Tx 172 created, waiting for 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
