### ISSUE TITLE
ACD meeting 127 notes

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#278]
PR: [ethereum-cat-herders/EIPIP#92](https://github.com/ethereum/pm/pull/431)
Amount: 100 DAI
Wallet: 0xEcebC7c42E3D16f70964d7d350FdFaE51ca5b5f6

I received 150 DAI instead of 100 DAI in the previous notes, so I'm adjusting it with this notes payout. Reference: https://github.com/ethereum-cat-herders/funding/issues/273

**Comment by poojaranjan** [comment]
Created multisig tx 173, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed
