### ISSUE TITLE
Funding for note-taking for Ethereum Cat Herders call #18 Tue Aug 27

### ISSUE THREAD

**Issue by BrentAllsop** [ethereum-cat-herders/funding#28]
Brent Allsop and Jim Bennett took notes for this,
and haven't been paid, as of Dec 12, 2019.

**Comment by timbeiko** [comment]
@BrentAllsop can you please add your ETH address and the number of DAI to send?

**Comment by BrentAllsop** [comment]
0xED4aD2e886C5c31D298d1de49256C40239180D16

This is an Ether Cat Herder meeting, so $50 dai.
It's the core dev cals (1.x and 2.0) that get $100 die.

**Comment by timbeiko** [comment]
Sent a total of 300 DAI for:

#31
#30
#29
#28
Multisig txn #54. https://etherscan.io/tx/0x76f6c7f8af0457c1918de45228430b1ccc2626f45e1c7dcf5a0ab511d889a9e8

**Comment by CPSTL** [comment]
[Confirmed ](https://etherscan.io/tx/0x682be7a0b9c6ee5ee621a5725275f5b7df77ff31f7df8ead25c7c3a63fc04fd7).
