### ISSUE TITLE
Catblazer + gas refund Dec '21

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#281]
amount: 0.40953944 ETH

address: `wschwab.eth`

breakdown of amount:

Nov month close for ETH (CoinGecko): $4624.86
Catblazer: 30 hrs x $50 = $1500, 4624.86/1500 = 0.324334142 ETH
Gas refunds: (multisig txs 220-224) 0.03942250667 ETH, (multisig txs 238-243) 0.04578279147 ETH
0.324334142+0.03942250667+0.04578279147 = 0.40953944

**Comment by poojaranjan** [comment]
multisig txs 151-155 & multisig txs 166-171

**Comment by poojaranjan** [comment]
Created multisig tx - 176

**Comment by poojaranjan** [comment]
tx completed
