### ISSUE TITLE
Funding for Consensus Layer Call #76 note and readme file

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#282]
- PR: [Consensus Layer Call #76 note and readme file](https://github.com/ethereum/pm/pull/426)

![image](https://user-images.githubusercontent.com/74140118/144760977-5c180a71-bc18-457c-bea2-555526516d0f.png)

![image](https://user-images.githubusercontent.com/74140118/144760924-47ccfaab-d520-41f3-9cf4-1b6a7339d7f6.png)

- Amount: -
    PR amount for Consensus Layer Call 76 note is 150 USD 
     PR amount for Readme file(migration from old repo, update  meeting from [Eth2.0 readme](https://github.com/ethereum/eth2.0-pm/blob/master/README.md) to [consensus-layer.md](https://github.com/Avishek041180/pm/blob/master/Consensus-Layer-Meetings/consensus-layer.md)) is 100 USD
- Total Amount : 250/4350.57=0.0575 ETH

Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Please elaborate and update the funding request.  

Created tx 177 for #283 & #282

**Comment by Avishek041180** [comment]
Please review

**Comment by poojaranjan** [comment]
tx completed
