### ISSUE TITLE
Funding for Consensus Layer Call 77 Notes

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/funding#285]
PR: https://github.com/ethereum/pm/pull/434

Wallet: 0x2f51E78ff8aeC6A941C4CEeeb26B4A1f03737c50

Amount: 0.0339366 ETH (150 USD / 4420 ETH = ~0.0339366)

![Screen Shot 2021-12-08 at 11 12 07 AM](https://user-images.githubusercontent.com/54918343/145242956-3821897f-10db-4d77-acf3-971ea94ec8f5.png)

**Comment by poojaranjan** [comment]
multisig tx 179 created. Waiting on 2nd approval.

**Comment by poojaranjan** [comment]
Tx completed, thanks for your patience!
