### ISSUE TITLE
Funding for ECH Meeting 073

### ISSUE THREAD

**Issue by mryalamanchi** [ethereum-cat-herders/funding#286]
- PR: [ECH Meeting 073](https://github.com/ethereum-cat-herders/PM/pull/254)

![14th_december](https://user-images.githubusercontent.com/12873030/146066378-503ec5c2-1c37-4486-9fd3-a554c5471a83.png)
- Amount: 50/3764.21 = 0.0132829 ETH ([Yahoo Finance, 14th Dec](https://finance.yahoo.com/quote/ETH-USD/history?period1=1639440000&period2=1639440000&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true))

- Wallet: 0x59b548e19cd84edb25fb48cc06fe0e9f16770358

**Comment by poojaranjan** [comment]
Created multisig tx 183 for #286 & #291. Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed, thanks!
