### ISSUE TITLE
Funding for Post Merge Mev

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#287]
-	PR : [Post Merge Mev](https://github.com/ethereum/pm/pull/447)

![image](https://user-images.githubusercontent.com/74140118/146616953-929acdcb-6bb2-4616-af08-acea970d49bc.png)

![image](https://user-images.githubusercontent.com/74140118/146616976-d872997f-f7aa-4caa-acdb-5fb4eea7fa9e.png)

-	Amount: 150/3859.35=0.0389 ETH

-	Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
created multisig tx 180, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
Tx completed, thanks for your patience!
