### ISSUE TITLE
Funding for EIP IP Meeting # 96

### ISSUE THREAD

**Issue by KinnShah** [ethereum-cat-herders/funding#289]
Meeting Date: Friday December 3, 2021
Pull Request Date: Monday December 13, 2021

PR: Add notes for meeting [# 96](https://github.com/ethereum-cat-herders/EIPIP/pull/96)
Amount: 0.023692 Eth = 100 /4220.71(see [Yahoo Finance](https://finance.yahoo.com/quote/ETH-USD/history?period1=1638489600&period2=1638489600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true) for a value on Monday December 13, 2021.)
Payable to canonizer.eth

**Comment by poojaranjan** [comment]
I am afraid, I do not see meeting 96. Can you plz link to the PR?
Also, the funds requested should be based on the date of submission of the PR. Thanks!

**Comment by poojaranjan** [comment]
Multisig tx 189 created, waiting on next confirmation.

**Comment by poojaranjan** [comment]
tx executed, thanks for your patience!
