### ISSUE TITLE
Funding for Community Call Meeting 02

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#290]
PR: https://github.com/ethereum/pm/pull/433

![image](https://user-images.githubusercontent.com/27824858/147077094-15d4f3a6-4044-4186-ac39-3adc5425b781.png)

100/4173.83= 0.02395892482 ETH

Wallet: 0x15De2EBE3879D2c7376a884Eed4D3b5A5BA53766

**Comment by Santhosh1692** [comment]
@poojaranjan Just to be sure, we're using the ERC20 network for payments? Otherwise, the wallet application that I use does not support it.

![image](https://user-images.githubusercontent.com/27824858/147077737-96f018ef-d8b5-462f-8257-2edd3c10cb9b.png)

**Comment by poojaranjan** [comment]
We are using Ethereum mainnet and it supports ERC-20 tokens.

**Comment by Santhosh1692** [comment]
@poojaranjan Noted, please proceed with the payout.

**Comment by poojaranjan** [comment]
Created multisig tx 184, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed, thanks!
