### ISSUE TITLE
ECH Eng (Dec 2021)

### ISSUE THREAD

**Issue by mryalamanchi** [ethereum-cat-herders/funding#291]
You can check the work completed in Dec, 2021 here:
https://github.com/ethereum/EIP-Bot/issues/31
https://github.com/ethereum/EIP-Bot/issues/37

Both tasks are included here: https://github.com/ethereum-cat-herders/PM/issues/259

• Total hours: 2
• Total Amount: $100/3,682.63 =  0.02715 ETH
• Wallet address (ETH Network): 0x59b548e19cd84edb25fb48cc06fe0e9f16770358
Ref: [Yahoo Finance](https://finance.yahoo.com/quote/ETH-USD/history?period1=1640908800&period2=1640908800&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true)

![ech_eng_2021](https://user-images.githubusercontent.com/12873030/147854834-6ba4bb8d-8d0e-4ec8-8bd4-45c9bd71b6da.png)

**Comment by poojaranjan** [comment]
Created multisig tx 183 for #286 & #291

**Comment by poojaranjan** [comment]
tx completed, thanks!
