### ISSUE TITLE
ECH Eng Dec 2021

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#292]
You can see the work completed this month here: 
https://github.com/ethereum-cat-herders/funding/issues/277

Amount: 40 hours * 50$ / hr = 2000$ = 2000 DAI
Address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Created multisig tx 185

**Comment by poojaranjan** [comment]
tx completed!
