### ISSUE TITLE
funding for Catblazer, Dec '21

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#293]
Hours: 30 (USD 1500)

Amount: 0.406023219 ETH

Wallet: `wschwab.eth`

On Price:
CoinGecko's price closest to 11:59PM Dec 31: $3694.37
1500 /3694.37 = 0.406023219

**Comment by poojaranjan** [comment]
Created multisig tx 186, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed.
