### ISSUE TITLE
Funding Request for ECH Meeting 074 Notes Task

### ISSUE THREAD

**Issue by ShubhangiSG** [ethereum-cat-herders/funding#296]
You can check the completed task [here:](https://github.com/ethereum-cat-herders/PM/pull/257/commits/ce93fd2dadc5519babd7e41f81e9042a03021369)

No. of hours = 1

Amount = 1*50 = 50 == (50/4,045.05) = 0.01236079 ETH

Coingecko closing price on 12/27/21 is 4,045.05 USD [](https://www.coingecko.com/en/coins/ethereum/historical_data/usd?start_date=2021-12-27&end_date=2021-12-28#panel)

Wallet - 0xc0bB46CBE12a833483289f11422583a06a8F28d8

**Comment by poojaranjan** [comment]
Created multisig tx 188, waiting for 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
