### ISSUE TITLE
Sell 12,950 DATA coin for DAI

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/funding#3]
I did this once previously (see row 4 of https://docs.google.com/spreadsheets/d/1PMCKHrkD2oGNXnDi6chy9DOFbpXgDRqpNz75PXSzoj4/edit#gid=0). I propose that we hold all of our funds in DAI and sell other tokens at current spot rates as they arrive. I'm happy to do this conversion, and will share all the tx details.

We received a donation of DATA a few days ago: https://etherscan.io/tx/0x1ebf62c6ebaf1ace17ada8086b2bbfef4d69656179da7c2c4a9dade145f33023.

Could someone please approve this?

**Comment by DBrettRobertson** [comment]
Approved.

**Comment by lrettig** [comment]
Transactions:

- https://etherscan.io/tx/0xe5a19ff89aedef8456b5b0de33445270399dcd7430a7fad84c970ab01fdf6cf4
- https://etherscan.io/tx/0x9bfebfb3c9587ec3e95bc6bd6ec7e899fb5cad9ca949b529e09c03b588031af7

Trade:

![image](https://user-images.githubusercontent.com/3316532/54238259-4626f280-4518-11e9-8524-8a266266cc5e.png)

Details in spreadsheet: https://docs.google.com/spreadsheets/d/1PMCKHrkD2oGNXnDi6chy9DOFbpXgDRqpNz75PXSzoj4/edit#gid=0
