### ISSUE TITLE
Funding for ACD Meeting 129 Notes

### ISSUE THREAD

**Issue by mryalamanchi** [ethereum-cat-herders/funding#301]
- [ACD Meeting 129 PR](https://github.com/ethereum/pm/pull/464)

![eth_price](https://user-images.githubusercontent.com/12873030/151141203-b9aea932-c12e-4314-8fe4-861b1bf9a840.png)
[yahoo finance](https://finance.yahoo.com/quote/ETH-USD/history?period1=1643068800&period2=1643068800&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true)

- Amount:  0.061076 ETH (at $2,455.94 USD/ETH => $150/$2,455.94 = ~0.061076 ETH)

- Wallet: 0x59b548e19cd84edb25fb48cc06fe0e9f16770358

**Comment by poojaranjan** [comment]
multisig tx 193 created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
tx executed, thanks for your patience!
