### ISSUE TITLE
Funding for Catblazer, Jan '22

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#302]
amount: 0.559265349 ETH

address: `wschwab.eth`

breakdown of amount:

Jan month close for ETH (CoinGecko): $2682.09
30 hrs x $55 = $1650, 1650/2682.09 = 0.615191884 ETH

**Comment by poojaranjan** [comment]
multisig tx 194 created, waiting for 2nd confirmation

**Comment by poojaranjan** [comment]
tx executed, thanks for your patience!
