### ISSUE TITLE
ECH Engineering January 2022

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#307]
You can see full ECH Engineering task list here: https://github.com/ethereum-cat-herders/PM/issues/261

I completed:
- https://github.com/alita-moore/PM/issues/9
- https://github.com/ethereum/EIP-Bot/issues/38
   - This bug has required extensive research, and it's not completely fixed yet. I am still working to find a suitable solution.
- https://github.com/ethereum/EIP-Bot/issues/33
- https://github.com/ethereum/EIP-Bot/issues/32
- https://github.com/ethereum/EIP-Bot/issues/47
- https://github.com/ethereum/EIP-Bot/issues/44
- helping new engineers get onboarded

Amount: 20 hours * 55$ / hr = 1100$ = 1100 DAI
Address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Created multisig tx 198, waiting on 2nd confirmation!

**Comment by poojaranjan** [comment]
TX completed, thanks for your cooperation!
