### ISSUE TITLE
Funding for ECH meeting 077.md

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#308]
- PR : [ECH meeting 077.md]

![image](https://user-images.githubusercontent.com/74140118/152927925-8da48842-e9ab-4e09-8893-fc0744395c7f.png)

![image](https://user-images.githubusercontent.com/74140118/152927951-00073405-fec2-4a9b-a58f-4961b799ded8.png)

- Amount: 50/3187.68=0.015685 ETH

Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
created multisig tx 199 for #312 and #308, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
TX completed, thanks for your cooperation!
