### ISSUE TITLE
Funding for EIP editor, December 2021

### ISSUE THREAD

**Issue by lightclient** [ethereum-cat-herders/funding#309]
Hours: 25

Amount: 1625 USDC

Wallet: 0xdf524fc9b23443de65f5f0695b8c1f86d13e9515

Thank you!

**Comment by poojaranjan** [comment]
Created multisig tx 200 for #310 and #309, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
TX completed, thanks for your cooperation!
