### ISSUE TITLE
Funding for Consensus Layer 81 notes

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/funding#311]
PR: https://github.com/ethereum/pm/pull/476#issue-1136004642
Wallet: 0x2f51E78ff8aeC6A941C4CEeeb26B4A1f03737c50
Amount: 0.05111 ETH (150 / 2934.63 = ~0.05111377)
<img width="971" alt="Screen Shot 2022-02-13 at 10 24 51 AM" src="https://user-images.githubusercontent.com/54918343/153760466-6c3e9df0-8061-4c67-ab5a-32928dd3c88e.png">

**Comment by poojaranjan** [comment]
multisig tx 201 created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
TX completed, thanks for your cooperation!
