### ISSUE TITLE
Funding for community call meeting #03

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#312]
-PR : [community call meeting #03](https://github.com/ethereum/pm/pull/480)

![image](https://user-images.githubusercontent.com/74140118/153950947-1d1852ca-8ff9-4312-8f25-16748c96b1b0.png)

![image](https://user-images.githubusercontent.com/74140118/153951029-f0e5b2c6-9fb6-4566-b4a6-034d7634ffbb.png)

- Amount: 100/2895.2=0.034539 ETH

- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
created multisig tx 199 for #312 and #308, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
TX completed, thanks for your cooperation!
