### ISSUE TITLE
Funding for EIP IP Meeting # 48

### ISSUE THREAD

**Issue by iamkinnarid** [ethereum-cat-herders/funding#313]
Meeting Date: Tuesday February 1, 2022
Pull Request Date: Thursday February 3, 2022

PR: Add notes for meeting https://github.com/ethereum-cat-herders/EIPIP/pull/108
Amount: 0.035815 Eth = 100 /2792.12(see [Yahoo Finance](https://finance.yahoo.com/quote/ETH-USD/history?period1=1643673600&period2=1643673600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true) for a value on Tuesday February 1, 2022.)
Payable to canonizer.eth

**Comment by poojaranjan** [comment]
Created multisig tx 202, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
Tx completed.
