### ISSUE TITLE
Funding for CL call #79 Notes

### ISSUE THREAD

**Issue by s-wuest** [ethereum-cat-herders/funding#314]
PR: https://github.com/ethereum/pm/pull/461
Date of commit: 21.01.2022 (I wasn't aware there is funding for these tasks so I didn't claim until now)
Wallet: wuest.eth
Amount: 0.0519606484688929 ETH (150 USD / 2886.80 USDETH = ~0.0519606484688929)

![image](https://user-images.githubusercontent.com/20667579/154032397-b631b2e5-74ea-4a9a-bcdf-acf1509b4500.png)

**Comment by poojaranjan** [comment]
multisig tx 203 created for #314 & #315, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
TX completed, thanks for your cooperation!
