### ISSUE TITLE
Funding for ACD meeting notes #131

### ISSUE THREAD

**Issue by s-wuest** [ethereum-cat-herders/funding#315]
PR: https://github.com/ethereum/pm/pull/474
Date of commit: 12.02.2022 (final version)
Wallet: wuest.eth
Amount: 0.0511824860357117 ETH (150 USD / 2930.69 USDETH = 0.0511824860357117)

![image](https://user-images.githubusercontent.com/20667579/154033424-0f8729f4-c22e-4cfa-a74c-851247c36ee3.png)

**Comment by poojaranjan** [comment]
multisig tx 203 created for #314 & #315, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
TX completed, thanks for your cooperation!
