### ISSUE TITLE
Consensus-layer Call 80

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#316]
PR: https://github.com/ethereum/pm/pull/483
Amount: 150 DAI
Wallet: 0x15De2EBE3879D2c7376a884Eed4D3b5A5BA53766

**Comment by poojaranjan** [comment]
Created multisig tx 205, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
TX completed, thanks for your cooperation!
