### ISSUE TITLE
Funding for ECH, EIPIP 49 and Learn2Earn (Jan - Feb 19th)

### ISSUE THREAD

**Issue by mryalamanchi** [ethereum-cat-herders/funding#317]
[ECH](https://github.com/ethereum/EIPs/pull/4619)

- Amount: 30 USDC

---

[EIPIP Meeting 49](https://github.com/ethereum-cat-herders/EIPIP/pull/111)

- Amount: 100 USDC

---

[Learn2Earn Dry Run, Jan - Feb 19th](https://github.com/ethereum-cat-herders/L2E/pull/2)

Total hours: 11 hours

- Amount: 660 USDC

---

Total: 790 USDC
Wallet: 0x59b548e19cd84edb25fb48cc06fe0e9f16770358

**Comment by poojaranjan** [comment]
Please create separate issues for each.

Add wallet address and breakdown details based on the task completed.
eg. 

1. for eip-bot work 
- Add reference links to PRs/tasks
- month
- no. of hrs * $55 USD/hr
- Total ask

2. for Learn2Earn
- Add reference links to PRs/tasks
- month
- no. of hrs * $50 USD/hr
- Total ask

3. Notes 
- Add reference links to PRs
- month
- no. of hrs * variable (depends on meeting)
- Total ask

Thanks for understanding!

**Comment by mryalamanchi** [comment]
Thank you, @poojaranjan, closing this issue and opening separate ones!
