### ISSUE TITLE
Funding for Meeting notes EIPIP50

### ISSUE THREAD

**Issue by s-wuest** [ethereum-cat-herders/funding#318]
Meeting Date: Wednesday, February 23, 2022
Pull Request Date: Thursday February 24, 2022

PR: Add notes for meeting https://github.com/ethereum-cat-herders/EIPIP/pull/113
Amount: 0.040932776101808 ETH = 100 /2443.03 (Value as of 24.02.2022, 18:56 CET coingecko)
Wallet: wuest.eth

![image](https://user-images.githubusercontent.com/20667579/155580494-83b92e1d-df83-4004-b676-c0c218ef57b2.png)

**Comment by poojaranjan** [comment]
Please use the ETH price of the date when PR is made. You may use closing rate of the day if the funding request is not made on the same day as of pull request.
https://www.coingecko.com/en/coins/ethereum/historical_data/usd#panel

**Comment by s-wuest** [comment]
Price was from today and pr as well. Updated it with the most recent price according to coingecko

**Comment by poojaranjan** [comment]
My bad, I mistakenly considered meeting date as the PR date :)

**Comment by poojaranjan** [comment]
Created multisig tx 204, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
TX completed, thanks for your cooperation!
