### ISSUE TITLE
Funding for ECH Meeting 78 Notes

### ISSUE THREAD

**Issue by amodernman** [ethereum-cat-herders/funding#319]
PR:https://github.com/ethereum-cat-herders/PM/pull/271 and https://github.com/ethereum-cat-herders/PM/pull/272
Amount: $50 in ETH
Wallet: 0x594687F6D113C5e80c67FA5458Dfa369B7A940D6

**Comment by poojaranjan** [comment]
Please use history of the ETH price on the day of PR submission. Use the closing price to calculate the amount to be paid in ETH.
You may use Coingecko closing price for reference. Thanks.

**Comment by amodernman** [comment]
Using Feb 16 closing price (3,179.30), that comes out to 0.01572673 ETH
Thanks!

**Comment by poojaranjan** [comment]
Multisig tx 211 created, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
Tx completed!
