### ISSUE TITLE
Funding for note-taking for 1.x Core Dev call #76  Fri Nov 15

### ISSUE THREAD

**Issue by BrentAllsop** [ethereum-cat-herders/funding#32]
Brent Allsop and Jim Bennett took notes for this,
and haven't been paid, as of Dec 12, 2019.

**Comment by timbeiko** [comment]
@brentallsop, can you please add your ETH address and number of DAI to send? Thanks!

**Comment by BrentAllsop** [comment]
0xED4aD2e886C5c31D298d1de49256C40239180D16

This was a core dev call so $100 DAI

Thanks

**Comment by timbeiko** [comment]
Multisig transaction was sent. #53 in the multisig. https://etherscan.io/tx/0xfe4ba0de22c84304562222909f083c2300b31b97c80319605c76e5a0dfec1cfd

**Comment by CPSTL** [comment]
[Confirmed](https://etherscan.io/tx/0xc7728f5887cfc3f0a1d763dc7882aa76b36a6418f09387a0b9e56b35337e2a38) and added to accounting database.
