### ISSUE TITLE
ECH Engineering (January)

### ISSUE THREAD

**Issue by mryalamanchi** [ethereum-cat-herders/funding#320]
You can check the work completed in Jan, 2022 here:
[Issue mentioned](https://github.com/ethereum-cat-herders/PM/issues/261)
[PR for issue](https://github.com/ethereum/EIPs/pull/4619)

• Total hours: 1
• Total Amount: 1 * $55 = **55 USDC**
• Wallet address (ETH Network): 0x59b548e19cd84edb25fb48cc06fe0e9f16770358

**Comment by poojaranjan** [comment]
multisig tx 210 created for #320 #321 #322. Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
Tx completed!
