### ISSUE TITLE
Learn2Earn (January)

### ISSUE THREAD

**Issue by mryalamanchi** [ethereum-cat-herders/funding#322]
[Learn2Earn Dry Run PR](https://github.com/ethereum-cat-herders/L2E/pull/2)

- Month: January (Claiming only for the January month)
- Total Hours worked: 8 hours
- Total Amount: 8 * $50 = **400 USDC**

**Comment by poojaranjan** [comment]
multisig tx 210 created for #320 #321 #322. Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
Tx completed!
