### ISSUE TITLE
Funding for Catblazer Feb '22

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#325]
amount: 0.584486661 ETH

address: `wschwab.eth`

breakdown of amount:

Feb month close for ETH (CoinGecko): $2822.99
30 hrs x $55 = $1650, 1650/2822.99 = 0.584486661 ETH

I'll bill separately for the ENS stuff (and funding the Mirror wallet) once that story is a bit more resolved

**Comment by poojaranjan** [comment]
> I'll bill separately for the ENS stuff (and funding the Mirror wallet) once that story is a bit more resolved

Sounds good.


Please add the link or screenshot for a quick ETH price reference. thanks!

**Comment by wschwab** [comment]
I was asked to reference my source for the price - using CoinGecko this was the closest price to 0000 Mar 1
![Screenshot from 2022-03-13 09-56-09](https://user-images.githubusercontent.com/31592931/158050657-f7fba738-5a99-4a63-b125-22dfa24334da.png)

**Comment by poojaranjan** [comment]
Multisig Tx 213 initiated, waiting on 2nd confirmation
