### ISSUE TITLE
Funding for ACD 133 meeting notes

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/funding#327]
PR: https://github.com/ethereum/pm/pull/493
Wallet: 0x2f51E78ff8aeC6A941C4CEeeb26B4A1f03737c50
Amount: 0.056153 ETH (150 / 2671.27 = ~0.05615306577)
<img width="955" alt="Screen Shot 2022-03-09 at 10 28 42 PM" src="https://user-images.githubusercontent.com/54918343/157583357-db3f2083-d788-447d-a1c3-e3a053585148.png">

**Comment by poojaranjan** [comment]
tx 214 completed!
