### ISSUE TITLE
Funding for ECH Meeting 79

### ISSUE THREAD

**Issue by ShubhangiSG** [ethereum-cat-herders/funding#330]
[Completed Task](https://github.com/ethereum-cat-herders/PM/pull/273/commits)

No. of hours = 1

Amount = 1*50 = 50 USD == 50 / 2,642.53 ETH = 0.01892126. 

Ethereum Coingecko Closing Price on March 5, 2022: 2,642.53 USD

Wallet: 0xe9d9fc3f3bb0647cbacac0d3d367a87c141f6625

**Comment by poojaranjan** [comment]
Multisig tx. 219 created for #338 #337 #335 #331 #330
Waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
Tx completed!
