### ISSUE TITLE
Funding for EIPIP Meeting 051

### ISSUE THREAD

**Issue by ShubhangiSG** [ethereum-cat-herders/funding#331]
[Completed Task](https://github.com/ethereum-cat-herders/EIPIP/pull/117)

No. of hours = 2

Amount = 2*50 = 100 USD == 100/ 3,002.85 ETH = 0.0333017 ETH

Coingecko closing price on March 22, 2022: 3,002.85 USD

Wallet: 0xe9d9fc3f3bb0647cbacac0d3d367a87c141f6625

**Comment by poojaranjan** [comment]
Tx completed!
