### ISSUE TITLE
Funding for Consensus Layer 84 Meeting Notes

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/funding#332]
PR: https://github.com/ethereum/pm/pull/506
Wallet: 0x2f51E78ff8aeC6A941C4CEeeb26B4A1f03737c50 (georgeh.eth)
Amount: 0.04564 ETH (150 / 3286.11 = ~0.04564668)

![Screen Shot 2022-03-31 at 2 39 25 PM](https://user-images.githubusercontent.com/54918343/161126989-47f5f7c6-2066-406d-9467-70b9e472c870.png)

**Comment by poojaranjan** [comment]
multisig tx 222 created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
Tx completed!
