### ISSUE TITLE
notes, EIPIP 53

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#339]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/127
- payable to `edson.eth`
- for amount 0.03214162 ETH ($100 in ETH)
<img width="1319" alt="Screen Shot 2022-04-14 at 4 58 45 AM" src="https://user-images.githubusercontent.com/34966228/163351185-71cb6fc5-cfcb-4be3-87ce-de1e75b6bc47.png">

**Comment by poojaranjan** [comment]
Multisig tx 218 created, waiting on 2nd approval.

**Comment by edsonayllon** [comment]
Recieved
