### ISSUE TITLE
Funding for ECH Meeting 83 Notes

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#345]
PR: https://github.com/ethereum-cat-herders/PM/pull/283
Amount: 50 ETH
Wallet address: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
I suppose you meant to have 50 in ETH. 
If so, please update with exchange rate on the day and share the equivalent ETH. Thanks!

**Comment by poojaranjan** [comment]
I have considered 
amount = (50/2730)ETH = 0.01831
multisig tx 224, completed!
