### ISSUE TITLE
ECH Podcast - Descript Pro Subscription Reimbursement  (Mar 2022) 

### ISSUE THREAD

**Issue by Sahil-Suri** [ethereum-cat-herders/funding#348]
Amount: $30
Item: 1 month of Descript Pro Reimbursement
Reason: Podcast Production

<img width="981" alt="Screen Shot 2022-05-05 at 10 14 11 AM" src="https://user-images.githubusercontent.com/77424419/166943340-793eae70-3dff-4031-8ce3-8d16c2fd9478.png">

**Comment by poojaranjan** [comment]
This can be paid in ETH/DAI/USDC.
Let us know your preference and if in ETH, the calculated amount. You may consider Coingecko closing rate for the day for ETH price.

**Comment by Sahil-Suri** [comment]
Price:

![SmartSelect_20220505-215421_Chrome.jpg](https://user-images.githubusercontent.com/77424419/167054113-661f1be1-25e7-4779-aed6-92fccd5798e9.jpg)

As of 21:55 EST 4/5/22 the price of ETH is ~2736.89

The estimated reimbursement in ETH is 0.01095...

**Comment by wschwab** [comment]
There's no address on this one - also, would you like to make this monthly, or bundle it into larger bricks (bi-monthly or quarterly)?

(Also - I can lay this out in the meantime, if you'd like, and then file the refund myself.)

**Comment by wschwab** [comment]
I've laid this out independently in the meantime
