### ISSUE TITLE
Funding for ACD 137 Meeting Notes

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/funding#350]
PR: https://github.com/ethereum/pm/pull/522
Wallet: georgeh.eth (0x2f51E78ff8aeC6A941C4CEeeb26B4A1f03737c50)
Amount: 0.05466851 ETH = $150 / 2743.81

<img width="959" alt="Screen Shot 2022-05-05 at 11 37 29 PM" src="https://user-images.githubusercontent.com/54918343/167063624-cd32062e-0028-4597-b75f-c04a4fb8ca5c.png">

**Comment by poojaranjan** [comment]
multisig tx 224, completed!
