### ISSUE TITLE
Funding for EIP editor, (Feb,Mar,April) 2022

### ISSUE THREAD

**Issue by lightclient** [ethereum-cat-herders/funding#353]
Hours: 25*3

Amount: 1660*3 = 4980 USDC

Wallet: 0xdf524fc9b23443de65f5f0695b8c1f86d13e9515

Thank you!

**Comment by poojaranjan** [comment]
multisig tx 227, waiting for 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
