### ISSUE TITLE
Funding for Consensus Layer Call 87

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/funding#354]
PR: https://github.com/ethereum/pm/pull/534
Wallet: georgeh.eth (0x2f51E78ff8aeC6A941C4CEeeb26B4A1f03737c50)
Amount: 0.07639769 (@$1963.41/ETH => $150 / $1963.41 = 0.076397695845493)

![Screen Shot 2022-05-24 at 2 32 38 PM](https://user-images.githubusercontent.com/54918343/170108076-877eb3d1-db5d-4aaf-b443-55bab7f8b018.png)

**Comment by poojaranjan** [comment]
multisig tx 228 is created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
