### ISSUE TITLE
Funding for consensus layer notes 88

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#359]
Amount: $150 in eth (0.0829)
PR: https://github.com/ethereum/pm/pull/541
<img width="488" alt="image" src="https://user-images.githubusercontent.com/67558925/172078835-8e717376-9ae8-4989-bb11-f326b97dac06.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/67558925/172078861-7bf62959-6e35-479b-b2fb-ac72f944fc04.png">

Wallet address: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
tx completed!
