### ISSUE TITLE
Funding for ECH Meeting #25

### ISSUE THREAD

**Issue by thesachinmittal** [ethereum-cat-herders/funding#36]
https://github.com/ethereum-cat-herders/PM/pull/107

Please review and fund. 

Amount: 50 DAI
Account: thesachinmittal.gitcoin.eth

**Comment by Souptacular** [comment]
Just to make things more clear please include the amount owed in the comment. This will be for 50 SAI.

**Comment by timbeiko** [comment]
First tx done: https://etherscan.io/tx/0x627a0f1ad33636492f40fe0468d81295ce2e86c50732bbc96a390d3c1527c6f3

#59 in the muiltisig

**Comment by Souptacular** [comment]
#59 Approved
https://etherscan.io/tx/0xd0d6ec15397761038ee7b5878fbf546259a36c679ffba433b5aa2951fa1fd904
