### ISSUE TITLE
ECH Meeting 86 notes

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#367]
Amount requested: $50 in eth (.0298)
PR: https://github.com/ethereum-cat-herders/PM/pull/295
<img width="453" alt="image" src="https://user-images.githubusercontent.com/67558925/173135818-09e40df3-701f-487d-b7b6-3b282a4216f8.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/67558925/173135943-df6d00f4-6c52-40e0-bee8-ec74687be01a.png">
Wallet address: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
multisig tx 232, completed!
