### ISSUE TITLE
EIPIP meeting 58

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#368]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/150
- payable to `edsonayllon.eth` (new wallet)
- for amount 100 USD in ETH, (0.089 ETH)

<img width="874" alt="Screen Shot 2022-06-22 at 10 34 57 AM" src="https://user-images.githubusercontent.com/34966228/175056239-0aa44320-53b2-45a6-a786-f8ee6c34c67f.png">

**Comment by poojaranjan** [comment]
multisig tx 232, completed!
