### ISSUE TITLE
Reimbursement for ECH domain renewal

### ISSUE THREAD

**Issue by CPSTL** [ethereum-cat-herders/funding#37]
Please send reimbursement to the following address:`0x7EBB71274C871143A8C3Ce56e804837684dDa0aA`

The conversion of CAD <> USD is approximately 1 USD = 1.32922 CAD. Based on this, the reimbursement will be **18.9886 SAI or DAI**. 

**Renewal Receipt**
<img width="545" alt="Screen Shot 2020-02-06 at 12 47 11 PM" src="https://user-images.githubusercontent.com/32653033/73963763-e7f8c000-48de-11ea-9f56-76be5db6e4a8.png">

**Comment by lrettig** [comment]
Confirmed the multisig tx, updated spreadsheet.

https://etherscan.io/tx/0x202bfe678be9493d49a15e14c24bb2398ef4cffb75c50db2aa46d6fa0b15de29
