### ISSUE TITLE
ACD 140 Funding Request

### ISSUE THREAD

**Issue by modernman-dot-eth** [ethereum-cat-herders/funding#371]
https://github.com/ethereum/pm/pull/557
$150 in ETH
0x594687F6D113C5e80c67FA5458Dfa369B7A940D6

**Comment by poojaranjan** [comment]
Please write the calculated amount in ETH.
ETH value to be considered as the value on the day when the pull request was committed.

**Comment by poojaranjan** [comment]
multisig tx 232, completed!
