### ISSUE TITLE
Funding for EIPIP meeting 59

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#375]
https://github.com/ethereum-cat-herders/EIPIP/pull/155
Amount: $100 in eth (0.08935)
![image](https://user-images.githubusercontent.com/67558925/177396800-7fe5c91d-64fc-42de-a02e-6540031fcd05.png)
![image](https://user-images.githubusercontent.com/67558925/177396995-c150bbbe-c286-4c03-9653-430d81be8760.png)
0.08935 eth
Wallet: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
Please create separate issues for each pull request.

**Comment by poojaranjan** [comment]
multisig tx 244 completed!
