### ISSUE TITLE
Funding for ACD meeting 141

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#376]
https://github.com/ethereum/pm/pull/567
Amount: $150 in eth (0.14852)
![image](https://user-images.githubusercontent.com/67558925/177397461-b85cf752-77de-4f02-8994-2adeac6f8a82.png)
![image](https://user-images.githubusercontent.com/67558925/177397548-524b9eda-ec37-4e24-98fd-fa63b4e8b037.png)
0.14852 eth
Wallet: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
multisig tx 244 completed!
