### ISSUE TITLE
Funding for Notes, ACD #78

### ISSUE THREAD

**Issue by thesachinmittal** [ethereum-cat-herders/funding#38]
Funding required for All Core Devs call 78. 100 SAI/DAI.

Payable to 0xd01f31684999d2D5e3925bFb0FaE32f6E359f0fA

Thank you.

**Comment by timbeiko** [comment]
First transaction sent: https://etherscan.io/tx/0x4474564be9ff296c1c8dc895fdeeb42c61c09153f3b199fc0df311ee03dcfdd1

Number 58 in the multisig.

**Comment by Souptacular** [comment]
#58 Approved
https://etherscan.io/tx/0x95b4cfa92d61134f2b21f96f4dbdc3571a5f293253d54b47ac5a4c4ed531c796
