### ISSUE TITLE
Funding for eipip meeting 60

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#380]
https://github.com/ethereum-cat-herders/EIPIP/pull/163
![image](https://user-images.githubusercontent.com/67558925/180108414-679c8ede-7918-45b1-8aca-725985ada308.png)
![image](https://user-images.githubusercontent.com/67558925/180108463-5c6ba557-4658-4b0b-9f7d-73e27af3c0d0.png)
0.06585 eth
Wallet address: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
multisig tx 244 completed!
