### ISSUE TITLE
Funding for L2E Quiz Creation April/Mai 2022

### ISSUE THREAD

**Issue by s-wuest** [ethereum-cat-herders/funding#381]
Days of Creation:
01.04.2022 (EIP-3675: Upgrade consensus to Proof-of-Stake), 1.5h of work, output: see Google Docs Link below
20.04.2022 (EIP-4361: Sign-In with Ethereum), 1.5h of work, output: see Google Docs Link below
20.04.2022 (EIP-721: Non-Fungible Token Standard), 1.5h of work, output: see Google Docs Link below
01.04.2022 (MEV & Flashbots), 1.5h of work, output: see Google Docs Link below

Pull Request Date: n/a - Submission directly to https://docs.google.com/spreadsheets/d/1erdzbBlAkWlloZRcLIB-E9OzxzPJGnl36PiFQHNzZvE/edit#gid=0

PR: No PR (see above)
Amount: 300USDC (4 x 1.5h at a rate of 50USD/h)
Wallet: wuest.eth

**Comment by poojaranjan** [comment]
Multisig tx 237 completed!
