### ISSUE TITLE
Funding for Merge community call 5 notes #578

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#382]
PR: https://github.com/ethereum/pm/pull/578
![image](https://user-images.githubusercontent.com/67558925/180301983-9b0ff048-7c6e-42a6-9fe0-c972a9c3f8e0.png)
![image](https://user-images.githubusercontent.com/67558925/180302035-c1e5542a-da8e-4edb-abf7-c903f52a028f.png)
0.0679 eth
Wallet address: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
multisig tx 244 completed!
