### ISSUE TITLE
July Podcast Production

### ISSUE THREAD

**Issue by zkdoof** [ethereum-cat-herders/funding#384]
Task Performed: Video Podcast
No. of Hours - 19.7 hrs
Amount Requested - 19.7*55 = $1083.5
Wallet: 0x4338Cde35ef899C49EFa9807776B1116B152D72C
Date for conversion: August 1st 2022, time 22:15
Source for Conversion: https://www.coinbase.com/converter/eth/usd

![CleanShot 2022-08-01 at 22 15 59](https://user-images.githubusercontent.com/96735069/182277282-69ccdce9-9e42-43d5-b666-6b638421a8f7.png)

**Comment by poojaranjan** [comment]
Unfortunately, the amount was not paid correctly. Below is the difference to be paid 

<img width="243" alt="image" src="https://user-images.githubusercontent.com/29681685/188224942-e1d7360a-9783-4d55-8729-7c036abce56b.png">

**Comment by poojaranjan** [comment]
multisig tx created for #384 #398 #399 #400

**Comment by poojaranjan** [comment]
Tx completed!
