### ISSUE TITLE
Funding for Notes, Eth2 #33

### ISSUE THREAD

**Issue by thesachinmittal** [ethereum-cat-herders/funding#39]
Funding required for Eth2 - [Call #33](https://github.com/ethereum/eth2.0-pm/pull/127). 100 SAI/DAI.

Payable to 0xd01f31684999d2D5e3925bFb0FaE32f6E359f0fA

Thank you.

**Comment by poojaranjan** [comment]
Notes for Eth2 calls are paid by Eth2.0 team at https://github.com/ethereum/eth2.0-pm.
