### ISSUE TITLE
Funding for ECH Meeting 90

### ISSUE THREAD

**Issue by ShubhangiSG** [ethereum-cat-herders/funding#391]
[Work completed](https://github.com/ethereum-cat-herders/PM/pull/307/commits/c3885a9968d1359099fd94802c0d4503c13b2496)

Amount = 50 USD

Ethereum Closing Price on August 8th, 2022: 1,802.93 USD

Amount in ETH = 50 / 1,802.93 = 0.02773263521 ETH

Wallet = 0xc0bB46CBE12a833483289f11422583a06a8F28d8

**Comment by poojaranjan** [comment]
multisig tx 251 created
