### ISSUE TITLE
Funding for Merge community call meeting #06

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#392]
-PR : [ Merge community call meeting #06](https://github.com/ethereum/pm/pull/607)

![image](https://user-images.githubusercontent.com/74140118/184914214-fb03df78-9b41-4be7-b2f0-d1792dbf2276.png)

![image](https://user-images.githubusercontent.com/74140118/184918252-07cc684f-b6be-4366-bbf5-49e773b5847a.png)

- Amount: 100/1874.46=0.053348 ETH

- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Multisig tx 252 created for #392 #394 #396

**Comment by poojaranjan** [comment]
Tx completed!
