### ISSUE TITLE
EIPIP 62 notes

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#393]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/172

- Payable to `edsonayllon.eth`
- For amount $100 in ETH, 0.052635 eth
<img width="1345" alt="Screen Shot 2022-08-16 at 11 47 09 PM" src="https://user-images.githubusercontent.com/34966228/185030482-844f7067-8072-42bd-b9c2-4d948f5c3d01.png">

**Comment by poojaranjan** [comment]
Multisig tx 253 created

**Comment by poojaranjan** [comment]
Tx completed!
