### ISSUE TITLE
Funding for ECH meeting 91 notes

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#396]
pr: https://github.com/ethereum-cat-herders/PM/pull/311
![image](https://user-images.githubusercontent.com/67558925/186997212-f578c592-a675-4549-97e6-5259b1aac29f.png)
![image](https://user-images.githubusercontent.com/67558925/186997273-ea96fa79-81ee-4f37-a99c-fd67e20b5ad3.png)
Amount: 0.03095975232 eth
Wallet address: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
multisig tx 254 created

**Comment by poojaranjan** [comment]
Tx completed!
