### ISSUE TITLE
Funding for Consensus layer #94

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#397]
-	PR: [Call 094]( https://github.com/ethereum/pm/pull/615)

![image](https://user-images.githubusercontent.com/74140118/188009325-cfd087a0-7d33-4318-8bef-a596c259690e.png)

![image](https://user-images.githubusercontent.com/74140118/188009364-075c46d8-a7c0-46ac-a105-d22da7949cbd.png)

-	Amount: 150/1577.14=0.095108 ETH
-	Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Multisig tx 252 created for https://github.com/ethereum-cat-herders/funding/issues/392 https://github.com/ethereum-cat-herders/funding/issues/394 https://github.com/ethereum-cat-herders/funding/issues/397

**Comment by poojaranjan** [comment]
Tx completed!
