### ISSUE TITLE
ECH Podcast - Descript Pro Subscription Reimbursement (August 2022)

### ISSUE THREAD

**Issue by zkdoof** [ethereum-cat-herders/funding#398]
Amount: $30
Item: 1 month of Descript Pro Reimbursement
Reason: Podcast Production
Wallet: 0x4338Cde35ef899C49EFa9807776B1116B152D72C
![CleanShot 2022-09-02 at 11 07 58](https://user-images.githubusercontent.com/96735069/188180000-ce9f0a54-913c-458e-8b91-55027b999dc5.png)

Conversion Source: https://coinmarketcap.com/currencies/ethereum/historical-data/
Using ETH rate of the last day of the month (closing price) 
August 31st 2022, closing: 1553.86
![CleanShot 2022-09-02 at 11 15 40](https://user-images.githubusercontent.com/96735069/188180868-37292d95-11c5-4d8b-a0d4-753cc091db15.png)

Requesting amount in ETH
ETH converted amount: 30/1553.86 = 0.01930676

**Comment by poojaranjan** [comment]
multisig tx created for #384 #398 #399 #400

**Comment by poojaranjan** [comment]
Tx completed!
