### ISSUE TITLE
August Podcast Production

### ISSUE THREAD

**Issue by zkdoof** [ethereum-cat-herders/funding#399]
Task Performed: Video Podcast
No. of Hours - 9.4 hrs
Wallet: 0x4338Cde35ef899C49EFa9807776B1116B152D72C

Conversion Source: https://coinmarketcap.com/currencies/ethereum/historical-data/
Using ETH rate of the last day of the month (closing price) 
August 31st 2022, closing: 1553.86
![CleanShot 2022-09-02 at 11 15 40](https://user-images.githubusercontent.com/96735069/188180868-37292d95-11c5-4d8b-a0d4-753cc091db15.png)

Amount Requested - 9.4*55 = $517
Requesting amount in ETH
ETH converted amount: 517/1553.86 = 0.33271981

**Comment by poojaranjan** [comment]
multisig tx created for #384 #398 #399 #400

**Comment by poojaranjan** [comment]
Tx completed!
