### ISSUE TITLE
ECH Arweave Backup (August 2022) 

### ISSUE THREAD

**Issue by zkdoof** [ethereum-cat-herders/funding#400]
Task Performed: Video Backup
No. of Hours - 17 hrs
Wallet: 0x4338Cde35ef899C49EFa9807776B1116B152D72C

Conversion Source: https://coinmarketcap.com/currencies/ethereum/historical-data/
Using ETH rate of the last day of the month (closing price) 
August 31st 2022, closing: 1553.86
![CleanShot 2022-09-02 at 11 15 40](https://user-images.githubusercontent.com/96735069/188180868-37292d95-11c5-4d8b-a0d4-753cc091db15.png)

Amount Requested - 17*55 = $935
Requesting amount in ETH
ETH converted amount: 935/1553.86 = 0.60172731

**Comment by poojaranjan** [comment]
multisig tx created for #384 #398 #399 #400

**Comment by poojaranjan** [comment]
Tx completed!
