### ISSUE TITLE
EIP-Bot May 2022

### ISSUE THREAD

**Issue by JEAlfonsoP** [ethereum-cat-herders/funding#405]
PR: https://github.com/ethereum/EIP-Bot/pull/86 (Merged)
PR: https://github.com/ethereum/EIP-Bot/pull/85 (Merged)

Total Hours: 10
50USD = 1 hour
ETH = 1,942.33 USD (May 31, 2022) 
Amount USD: 50 x 10 = 500 USD
ETH = 500 / 1,942.33 = 0.25742 ETH
Ethereum Wallet:  0xC5f216513Fe89E6bc91E575ae6A3A86f582fa758

 
[Ethereum price today, ETH to USD live, marketcap and chart _ CoinMarketCap_May.pdf](https://github.com/ethereum-cat-herders/funding/files/9508658/Ethereum.price.today.ETH.to.USD.live.marketcap.and.chart._.CoinMarketCap_May.pdf)

**Comment by poojaranjan** [comment]
Please update it as per ETH price on the last day of the month. In this case, you may consider closing price of ETH on May 31.

**Comment by poojaranjan** [comment]
Multisig tx 257 completed for #405 & #406
