### ISSUE TITLE
EIP-Bot August 2022

### ISSUE THREAD

**Issue by JEAlfonsoP** [ethereum-cat-herders/funding#406]
PR: https://github.com/ethereum/EIP-Bot/pull/88 (Merged)

Total Hours: 5
50USD = 1 hour
ETH = 1,553.68 USD (August 31, 2022)
Amount USD: 50 x 5 = 250 USD
ETH = 250 / 1,553.68 =  0.16090 ETH
Ethereum Wallet: 0xC5f216513Fe89E6bc91E575ae6A3A86f582fa758

[Ethereum price today, ETH to USD live, marketcap and chart _ CoinMarketCap.pdf](https://github.com/ethereum-cat-herders/funding/files/9508684/Ethereum.price.today.ETH.to.USD.live.marketcap.and.chart._.CoinMarketCap.pdf)

**Comment by poojaranjan** [comment]
(same comment as #405 )

**Comment by poojaranjan** [comment]
Multisig tx 257 completed for #405 & #406
