### ISSUE TITLE
Funding for CL #93

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#408]
PR: https://github.com/ethereum/pm/pull/610
Amount: 150/1863 = 0.08051529791 ETH
Wallet: 0x15De2EBE3879D2c7376a884Eed4D3b5A5BA53766

<img width="918" alt="image" src="https://user-images.githubusercontent.com/27824858/189729785-397fc637-d805-47fe-a270-3e1b4bc096a4.png">

**Comment by poojaranjan** [comment]
Multisig tx 263 created for #408 #409 #410 #411 #415 #420 #421
waiting 2nd confirmation
