### ISSUE TITLE
Funding for CL-95

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#409]
PR: https://github.com/ethereum/pm/pull/620
Amount: 150/1725 = 0.08695652174 ETH
Wallet: 0x15De2EBE3879D2c7376a884Eed4D3b5A5BA53766

<img width="870" alt="image" src="https://user-images.githubusercontent.com/27824858/189730620-378e19c5-389d-4b19-a922-c5ae57913177.png">

**Comment by poojaranjan** [comment]
Multisig tx 263 created for #408 #409 #410 #411 #415 #420 #421
waiting 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
