### ISSUE TITLE
Funding for note-taking of ACD 81 

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#41]
Meeting: ACD meeting 81 
Notes location: https://github.com/ethereum/pm/blob/25bd9c2223635c3c3c5f4643fd924f6b44db62a6/All%20Core%20Devs%20Meetings/Meeting%2081.md
Amount: 100 SAI
Wallet: (ranjan.eth)
0xf13e477365B0FAa64130DA2FF663aAb20d32d929

Thanks!

**Comment by timbeiko** [comment]
Multisig txn 1 sent: https://etherscan.io/tx/0x49a499d77fcf15c3f51a0cc00cd2f149617fe193f292b9200da1e9235913e6a0

**Comment by Souptacular** [comment]
Approved!
