### ISSUE TITLE
Funding for Ethereum Core Devs Meeting 146

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#410]
PR: https://github.com/ethereum/pm/pull/621
Amount: 150/1725 = 0.08695652174 ETH
Wallet: 0x15De2EBE3879D2c7376a884Eed4D3b5A5BA53766
<img width="901" alt="image" src="https://user-images.githubusercontent.com/27824858/189731124-a72a2a3e-49f5-45a4-af04-24afd94a03de.png">

**Comment by poojaranjan** [comment]
Multisig tx 263 created for #408 #409 #410 #411 #415 #420 #421
waiting 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
