### ISSUE TITLE
Funding for Merge community call meeting #07

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#412]
-	PR : [Merge community call meeting #07](https://github.com/ethereum/pm/pull/622)

![image](https://user-images.githubusercontent.com/74140118/190056690-6d84705e-60fe-46bc-bca1-9be851cb0742.png)

![image](https://user-images.githubusercontent.com/74140118/190056735-3b1cf33b-802a-4458-aa98-50fa97c70b9a.png)

-	Amount: 100/1603.57=0.062360 ETH
-	Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
multisig tx 264 created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
