### ISSUE TITLE
Funding for EIPIP meeting notes 64

### ISSUE THREAD

**Issue by MetagoSG** [ethereum-cat-herders/funding#414]
[Work Completed](https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20064.md)
Amount = 100 USD
Ethereum closing price on September 16 = 1432.75 USD
Amount in ETH = (100/1432.75) USD = 0.06979584714

Wallet: 0xe9d9fc3f3bb0647cbacac0d3d367a87c141f6625

**Comment by poojaranjan** [comment]
multisig tx 265 created

**Comment by poojaranjan** [comment]
tx completed!
