### ISSUE TITLE
Funding ECH 93

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#415]
PR: https://github.com/ethereum-cat-herders/PM/pull/318
Amount: 50/1382 = 0.03617945007 ETH
Wallet: 0x15De2EBE3879D2c7376a884Eed4D3b5A5BA53766
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/27824858/192478082-39f98913-179b-41e4-82eb-8d24cc4ed24f.png">

**Comment by poojaranjan** [comment]
Multisig tx 263 created for #408 #409 #410 #411 #415 #420 #421
waiting 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
