### ISSUE TITLE
funding for acd meeting 147 

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#417]
pr: https://github.com/ethereum/pm/pull/635
![image](https://user-images.githubusercontent.com/67558925/193344445-2a24748e-5954-478d-9060-ef9014efaa0b.png)
![image](https://user-images.githubusercontent.com/67558925/193344385-b210ae56-3112-475c-8b92-dabeffdb06eb.png)
![image](https://user-images.githubusercontent.com/67558925/193345545-e4d03cea-945c-49eb-b210-059bd8b01799.png)
Amount in eth: 0.116913484
Wallet address: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
Multisig tx 266 created, waiting on 2nd approval.

**Comment by poojaranjan** [comment]
tx completed!
