### ISSUE TITLE
ECH Arweave Backup (September 2022)

### ISSUE THREAD

**Issue by zkdoof** [ethereum-cat-herders/funding#418]
Task Performed: Video Backup
No. of Hours - 14 hrs
Wallet: 0x4338Cde35ef899C49EFa9807776B1116B152D72C

Conversion Source: https://coinmarketcap.com/currencies/ethereum/historical-data/
Using ETH rate of the last day of the month (closing price)
September 30th 2022, closing: 1327.98
![CleanShot 2022-10-01 at 11 38 00](https://user-images.githubusercontent.com/96735069/193417120-6e8d932b-4e12-4914-8f4f-b0be4f8f66d4.png)

Amount Requested - 14*55 = $770
Requesting amount in ETH
ETH converted amount: 770/1327.98 = 0.57982801

For updates backup progress please track: https://hackmd.io/HLKt4BPVRg2LgT8KgQuTwA?view
Content backed up and available for view at ECH lenstube account https://lenstube.xyz/ethcatherders.lens
Videos backed up: PEEPanEIP episodes 14-34

**Comment by poojaranjan** [comment]
multisig tx 267 created for #418 #419
waitnf for 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
