### ISSUE TITLE
September Podcast Production

### ISSUE THREAD

**Issue by zkdoof** [ethereum-cat-herders/funding#419]
Task Performed: Video Podcast
No. of Hours - 2.746 hrs
Wallet: 0x4338Cde35ef899C49EFa9807776B1116B152D72C

Conversion Source: https://coinmarketcap.com/currencies/ethereum/historical-data/
Using ETH rate of the last day of the month (closing price)
September 30th 2022, closing: 1327.98
![CleanShot 2022-10-01 at 11 38 00](https://user-images.githubusercontent.com/96735069/193418108-14576699-16f5-4af6-a567-4b03a73ae971.png)

Amount Requested - 2.746*55 = $151.03
Requesting amount in ETH
ETH converted amount: 151.03/1327.98 = 0.11372912

Podcast:
https://anchor.fm/ethereum-cat-herders/episodes/PEEPanEIP-85-Ethereum-JS-and-The-Merge-with-Gajinder-Singh-e1niitp
https://open.spotify.com/show/7dgxKMkSyy3HWtQW7OfqXA

**Comment by poojaranjan** [comment]
multisig tx 267 created for #418 #419
waitnf for 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
