### ISSUE TITLE
Funding for L2E (from Genesis through October 2022)

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/funding#424]
This is funding for development and contribution to Learn2Earn (L2E) up to October 31, 2022

Repo: https://github.com/ethereum-cat-herders/L2E
Amount: 5000 USDC (100 hours @ $50/hr)
Wallet: georgeh.eth (0x2f51E78ff8aeC6A941C4CEeeb26B4A1f03737c50)

**Comment by poojaranjan** [comment]
Multisig tx 275 created; waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
Tx completed!
