### ISSUE TITLE
ECH website update Sep 2022

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#428]
Below is the list of Issues resolved & pages updated:

- https://github.com/ethereum-cat-herders/ech-website-v2/issues/65
- https://github.com/ethereum-cat-herders/ech-website-v2/issues/66
- https://github.com/ethereum-cat-herders/ech-website-v2/issues/67
- https://github.com/ethereum-cat-herders/ech-website-v2/issues/69
- https://github.com/ethereum-cat-herders/ech-website-v2/issues/70
- Misc. (Bug fixes for 64)

Total Hours: 14 hrs. 
Amount =  (14*50) = 700 USD = 700/1345.44 =  0.52027589 ETH
Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

<img width="558" alt="image" src="https://user-images.githubusercontent.com/97191248/199844570-3e4d1b4a-c3f4-4231-8516-ef0931164b10.png">

<img width="343" alt="image" src="https://user-images.githubusercontent.com/97191248/199844813-5ca75e9a-4bf8-46cf-ab45-dff468aeccb7.png">

**Comment by poojaranjan** [comment]
tx 271 created for #428  #429; waiting on 2nd approval

**Comment by poojaranjan** [comment]
Tx completed!
