### ISSUE TITLE
ECH website update Oct 2022

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#429]
Below is the list of Issues resolved, page updated:

- Shanghai page (Readiness checklist), Merge page updating (Merge video) (75)

Total Hours:  1 hr.
Amount = (1*50) USD = 50 USD = 50/1,572.98 ETH = 0.03178679 ETH
Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

(Coingecko: Oct 31, 2022 closing = $1,572.98)

**Comment by poojaranjan** [comment]
tx 271 created for #428  #429
