### ISSUE TITLE
Funding for Notes, ACD 82

### ISSUE THREAD

**Issue by thesachinmittal** [ethereum-cat-herders/funding#43]
Meeting: ACD meeting 82
Notes: https://github.com/ethereum/pm/pull/156
Amount: 200 SAI (Since the call was 3 hrs long)

Payable to: 

1. 100$ (0xd01f31684999d2D5e3925bFb0FaE32f6E359f0fA): Sachin
2. 100$ (0xED4aD2e886C5c31D298d1de49256C40239180D16): Brent

Thanks!

**Comment by timbeiko** [comment]
Two first multisig txns:
* https://etherscan.io/tx/0x220adfb1f056d28e108724f99277dcc9f1d9e735f59cf21bf8e3402e8fdd601b
* https://etherscan.io/tx/0x4c80ddc434087639cb925eee41a6c34fb228945b44a49d38295cf2cf43f6472b

**Comment by timbeiko** [comment]
@thesachinmittal can you confirm that you received the funds here and close the issue if so? Thanks!

**Comment by BrentAllsop** [comment]
@brentallsop received his funds, and I assume @thesachinmittal, so am OK with closing this issue.
