### ISSUE TITLE
October Podcast Production 

### ISSUE THREAD

**Issue by zkdoof** [ethereum-cat-herders/funding#431]
Task Performed: Video Podcast
No. of Hours -3.54 hrs
Wallet: 0x4338Cde35ef899C49EFa9807776B1116B152D72C

Conversion Source: https://coinmarketcap.com/currencies/ethereum/historical-data/
Using ETH rate of the last day of the month (closing price)
October 31st 2022, closing: 1572.71

![CleanShot 2022-11-05 at 11 16 15@2x](https://user-images.githubusercontent.com/96735069/200127042-7fa049c9-bede-4d4d-87fd-86983fcd39db.png)

Amount Requested - 3.54*55 = $194.7
Requesting amount in ETH
ETH converted amount: 194.7/1572.71 = 0.12379905

Podcast:
https://anchor.fm/ethereum-cat-herders/episodes/PEEPanEIP-86-EIP-5496-Multi-privilege-Management-NFT-Extension-with-Allister-Capati-e1prjiv
https://open.spotify.com/episode/3wdBahtbo4YMHAmRtnLo3g

**Comment by poojaranjan** [comment]
Multisig tx 270 created, waiting on 2nd approval.

**Comment by poojaranjan** [comment]
Tx completed!
