### ISSUE TITLE
Bounty for Notes ECH meeting #97

### ISSUE THREAD

**Issue by Henryjk4** [ethereum-cat-herders/funding#435]
Bounty for Notes ECH meeting #97
PR link: https://github.com/ethereum-cat-herders/PM/pull/325
Amount: $50.00 USD = 0.03903505347802326 Eth. 
<img width="1440" alt="Screen Shot 2022-11-15 at 10 57 24 AM" src="https://user-images.githubusercontent.com/96284922/201938200-1a365c5b-edeb-422d-9ff8-a7102d6c4cdd.png">
Wallet: 0x5E47556aE689B0ad283D52a74742770b4b51e77E

**Comment by poojaranjan** [comment]
Updated PR https://github.com/ethereum-cat-herders/PM/pull/329

**Comment by poojaranjan** [comment]
Multisig tx 284 for #435 #451 waiting on confirmation!

**Comment by poojaranjan** [comment]
tx completed!
