### ISSUE TITLE
Funding for ECH 96

### ISSUE THREAD

**Issue by arredr2** [ethereum-cat-herders/funding#438]
PR: https://github.com/ethereum-cat-herders/PM/pull/324
Amount: 50 USDC
Wallet: 0x225a0871fe471a294de1324213e7029a1f81978f

**Comment by poojaranjan** [comment]
Multisig tx 283 created for #437 #438 #449 #453 waiting for confirmation!

**Comment by poojaranjan** [comment]
tx completed!
