### ISSUE TITLE
Funding for ECH Meeting #25

### ISSUE THREAD

**Issue by BrentAllsop** [ethereum-cat-herders/funding#44]
Brent Allsop

Took notes for ECH Meeting # 25 

$50

0xED4aD2e886C5c31D298d1de49256C40239180D16

**Comment by poojaranjan** [comment]
Please add the link to PR for ECH meeting 25.

**Comment by BrentAllsop** [comment]
This was unintentionally or mistakenly created, while creating a funding issue for meeting # 24.
https://github.com/ethereum-cat-herders/funding/issues/45
Since that is the correct issue, and this is an error, I'm closing this issue.
Sorry about the mess up.
