### ISSUE TITLE
ECH Arweave Backup (November 2022)

### ISSUE THREAD

**Issue by zkdoof** [ethereum-cat-herders/funding#442]
Task Performed: Video Backup
No. of Hours - 2 hrs
Wallet: 0x4338Cde35ef899C49EFa9807776B1116B152D72C

Conversion Source: https://coinmarketcap.com/currencies/ethereum/historical-data/
Using ETH rate of the last day of the month (closing price)
November 30th 2022, closing: $1295.69

![CleanShot 2022-12-01 at 08 49 42@2x](https://user-images.githubusercontent.com/96735069/205072582-11f20bad-231f-4bab-8f4a-a633679aa122.png)

Amount Requested - 2*55 = $110
Requesting amount in ETH
ETH converted amount: 110/1295.69 = 0.08489685

For updates backup progress please track: https://hackmd.io/HLKt4BPVRg2LgT8KgQuTwA?view
Content backed up and available for view at ECH lenstube account https://lenstube.xyz/ethcatherders.lens
Videos backed up: PEEPanEIP episodes 34-38

**Comment by poojaranjan** [comment]
multisig tx 281 created for #441 #442, waiting on confirmation!

**Comment by poojaranjan** [comment]
tx completed!
