### ISSUE TITLE
Funding for notes for ECH Meeting #24

### ISSUE THREAD

**Issue by BrentAllsop** [ethereum-cat-herders/funding#45]
Brent Allsop

Took notes for ECH Meeting # 24 
https://github.com/ethereum-cat-herders/PM/pull/100

$50

0xED4aD2e886C5c31D298d1de49256C40239180D16

**Comment by CPSTL** [comment]
Multisig Tx (#65): 

https://etherscan.io/tx/0x9f40d5277b9ad94782e9b6b83eb96776e85285aadad09f56cf54c10459b0a16b

cc @Souptacular @timbeiko for confirmation.

**Comment by timbeiko** [comment]
Confirmation sent: https://etherscan.io/tx/0x88cd388632c0e558c9a15591391ec44e09e3077f33f09d93add719bc57e37801
