### ISSUE TITLE
Funding for ACD meeting 150 notes

### ISSUE THREAD

**Issue by Henryjk4** [ethereum-cat-herders/funding#451]
PR: (https://github.com/ethereum/pm/pull/682)
Amount: 0.11950477222390414 ETH
Wallet: 0x5E47556aE689B0ad283D52a74742770b4b51e77E

**Comment by poojaranjan** [comment]
Multisig tx 284 for #435 #451 waiting on confirmation!

**Comment by poojaranjan** [comment]
tx completed!
