### ISSUE TITLE
Funding for ACD(E) 152

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#459]
PR: https://github.com/ethereum/pm/pull/706
Amount: 150/1309 = 0.1145912911
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB

![image](https://user-images.githubusercontent.com/27824858/211266044-58e915b1-5ea5-49a6-b424-c00dc8a01599.png)

**Comment by poojaranjan** [comment]
tx 284 initiated for
https://github.com/ethereum-cat-herders/funding/issues/448 https://github.com/ethereum-cat-herders/funding/issues/447 https://github.com/ethereum-cat-herders/funding/issues/439 https://github.com/ethereum-cat-herders/funding/issues/436 https://github.com/ethereum-cat-herders/funding/issues/434 https://github.com/ethereum-cat-herders/funding/issues/459
waiting on confirmation!

**Comment by poojaranjan** [comment]
tx completed!
