### ISSUE TITLE
Funding for note-taking of EIPIP call #02

### ISSUE THREAD

**Issue by BrentAllsop** [ethereum-cat-herders/funding#46]
Meeting: EIPIP call #2
Notes location: https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20003.md
Amount: 100 SAI
Wallet:
0xED4aD2e886C5c31D298d1de49256C40239180D16

Thanks.

**Comment by timbeiko** [comment]
First multisig txn sent (#66): 0x2abf6c3971e92ebab9cb7a0ddf02db5feb7e0ee7f1a9150bfaea31b84b801322

@CPSTL @Souptacular @lrettig can you please send the next one? Thanks!

**Comment by CPSTL** [comment]
Confirmed and added to the spreadsheet: https://etherscan.io/tx/0xc80e67c13b42b6f439a48965d57325dbb0b77f807327e235233674e661c20ec8
