### ISSUE TITLE
December Podcast Production

### ISSUE THREAD

**Issue by zkdoof** [ethereum-cat-herders/funding#460]
Task Performed: Video Podcast
No. of Hours -1.54 hrs
Wallet: 0x4338Cde35ef899C49EFa9807776B1116B152D72C

Conversion Source: https://coinmarketcap.com/currencies/ethereum/historical-data/
Using ETH rate of the last day of the month (closing price)
December 31st 2022, closing: $1,196.77

![Capture 2023-01-09 at 09 53 49@2x](https://user-images.githubusercontent.com/96735069/211337333-1f4595aa-2a14-4b1c-8424-7df7b4c6ad97.png)

Amount Requested - 1.54*55 = $84.7
Requesting amount in ETH
ETH converted amount: 84.7/1,196.77 = 0.07077383

Podcasts:
PEEPanEIP 90 https://open.spotify.com/episode/6Sdcs9hqw5hhn573IYwTTB
PEEPanEIP 91 https://open.spotify.com/episode/1n6O3cbMEivB65lRWVLH9U
PEEPanEIP 92 https://open.spotify.com/episode/21VMZRosVnHzvPz8onXiBY

**Comment by poojaranjan** [comment]
multisig tx 286 created for #441 #442 #460, waiting on confirmation!

**Comment by poojaranjan** [comment]
tx completed!
