### ISSUE TITLE
Funding EIPIP 72

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#465]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/209
- Payable to `edsonayllon.eth`
- For amount: 100 USD in ETH, or 0.06398 ETH

<img width="1308" alt="Screenshot 2023-01-16 at 11 21 47 PM" src="https://user-images.githubusercontent.com/34966228/212809423-306b94ce-3d43-4019-9935-baeaab7c2c9e.png">

**Comment by poojaranjan** [comment]
Multisig tx 300 created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
Tx completed!
