### ISSUE TITLE
$50 Funding for ECH Meeting #28

### ISSUE THREAD

**Issue by BrentAllsop** [ethereum-cat-herders/funding#47]
$50 for taking notes for ECH Meeting #28.

Here is the pull request:
https://github.com/ethereum-cat-herders/PM/pull/111

Deposit Address:
0xED4aD2e886C5c31D298d1de49256C40239180D16

**Comment by timbeiko** [comment]
First multisig txn sent (#67): 0x60558f579a9283c5a5b5a78651ff29a8fa61ce1933c94aadbbc0443570bc4602

@CPSTL @Souptacular @lrettig can you please send the next one? Thanks!

**Comment by CPSTL** [comment]
Confirmed and added to the spreadsheet: https://etherscan.io/tx/0x742ffd88c82fc438d77f10a5f34a0fbd7a0b5f7d383af17c7329da6f1a7f2b2b
