### ISSUE TITLE
Funding for Shanghai - Capella Community Call 01

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#470]
PR: https://github.com/ethereum/pm/pull/717
Amount: 100/1592 = 0.06281407035
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB

![image](https://user-images.githubusercontent.com/27824858/216820959-5f176f25-bc9a-4ed2-85b5-a1a69a28a7bf.png)

**Comment by poojaranjan** [comment]
Multisig id 284 created for #463 #467 #469 #470. Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed
