### ISSUE TITLE
Funding for Consensus Layer Meeting #102

### ISSUE THREAD

**Issue by arredr2** [ethereum-cat-herders/funding#473]
PR: https://github.com/ethereum/pm/pull/723
Amount: 150 USDC
Wallet: 0x225a0871fe471a294de1324213e7029a1f81978f

**Comment by poojaranjan** [comment]
multisig tx 298 created for #471 #473, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
Tx completed!
