### ISSUE TITLE
Funding for ECH Meeting 101

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#474]
PR: https://github.com/ethereum-cat-herders/PM/pull/338/commits
Wallet address: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94
![image](https://user-images.githubusercontent.com/67558925/218284674-ead23d66-dd09-43f1-8840-d42a2f044c01.png)
![image](https://user-images.githubusercontent.com/67558925/218284689-e936786e-d332-42df-b9b4-8405d1fade07.png)
![image](https://user-images.githubusercontent.com/67558925/218284707-7a672d2c-2e83-460b-95c4-6e2d6f3aef3a.png)
Amount in eth: 0.03244646334

**Comment by poojaranjan** [comment]
multisig tx 296 created. Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
Tx completed!
