### ISSUE TITLE
ECH Ops Dec 2022 

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#476]
#### ECH website update

- https://github.com/ethereum-cat-herders/ech-website-v2/issues/83

Commit for website update with

[PR](https://github.com/ethereum-cat-herders/ech-website-v2/pulls?q=is%3Apr+author%3ASamarth-001) - 85

Total Hours: 2 hrs 

Amount = (2*50) USD = 100 USD = (100/1199.11) ETH =  0.083395 ETH

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718
<img width="1158" alt="Screenshot 2023-02-20 at 4 23 55 PM" src="https://user-images.githubusercontent.com/97191248/220200561-d1c72492-cc12-454b-a31f-7f3e4f819973.png">

**Comment by poojaranjan** [comment]
Created multisig tx 301, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
completed
