### ISSUE TITLE
ECH Ops Jan 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#477]
### 1. ECH website update (Tech)

- https://github.com/ethereum-cat-herders/ech-website-v2/issues/88
- other bug fixes

[PR](https://github.com/ethereum-cat-herders/ech-website-v2/pulls?q=is%3Apr+author%3ASamarth-001) - 89, 91

### 2. New feature addition for L2E project (Tech)

- Commit for updating L2E 
[PR](https://github.com/ethereum-cat-herders/L2E/pulls?q=is%3Apr+author%3ASamarth-001) - 30 & 25 merged with PR-34

### 3. ECH Anniv video (Ops)

https://youtu.be/dnQJvEj3Y1M

Total Hours: (4+4) hrs + 5 hrs 

Amount = 8 * 55 + 5 * 50 = 690 USD = (690/1586.54) ETH = 0.4349 ETH

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

<img width="1142" alt="Screenshot 2023-02-20 at 6 55 06 PM" src="https://user-images.githubusercontent.com/97191248/220214745-4d927ac3-5c39-4e3c-b0c1-91de110b2b6c.png">

**Comment by poojaranjan** [comment]
Created multisig tx 301, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
completed
