### ISSUE TITLE
funding for EIPIP meeting 75

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#479]
- PR: [EIPIP Meeting 75](https://github.com/ethereum-cat-herders/EIPIP/pull/218)

![image](https://user-images.githubusercontent.com/74140118/222278685-044e86ef-e7d4-4395-9de7-b3d4faaeb100.png)

![image](https://user-images.githubusercontent.com/74140118/222279060-0dc349ec-ba48-418a-8171-97f6cbf12e60.png)

- Amount: 100/1656.11 = 0.06038 ETH
- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Multisig txcreated for #479 #480
Waiting on second confirmation.

**Comment by poojaranjan** [comment]
Tx completed
