### ISSUE TITLE
$50 funding for ECH call 29

### ISSUE THREAD

**Issue by thesachinmittal** [ethereum-cat-herders/funding#48]
$50 for taking notes for ECH Meeting 29.

Here is the pull request:
https://github.com/ethereum-cat-herders/PM/pull/113

Payable to -> Sachin Mittal

Deposit Address:
0xd01f31684999d2D5e3925bFb0FaE32f6E359f0fA

**Comment by timbeiko** [comment]
First multisig txn sent (#68): 0x606763318ba0e9e2dbc7fa14f9070284c5bffd6852670b5c3df9b48043d1d118 

@CPSTL @Souptacular @lrettig can you please send the next one? Thanks!

**Comment by thesachinmittal** [comment]
Hey @lrettig @CPSTL @Souptacular any updates on this?

**Comment by CPSTL** [comment]
@thesachinmittal Also confirmed: https://etherscan.io/tx/0x829f4d63b875f8d475eab4695c2984ce5d0228e3ba194e2ffd23b5efc51b2dc4
