### ISSUE TITLE
Funding for Consensus-layer Call 103 Notes

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#486]
PR: https://github.com/ethereum/pm/issues/731
Amount: 150/1703 = 0.08807985907
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB

![image](https://user-images.githubusercontent.com/27824858/229350280-c26a551b-addd-4557-8570-6b32898c14ba.png)

**Comment by poojaranjan** [comment]
Multisig tx 304 created for #483 #484 #485 #486 #487 #490 #491
Waiting in 2nd approval

**Comment by poojaranjan** [comment]
Tx completed
