### ISSUE TITLE
Funding for Execution Layer Meeting #155

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#487]
PR: https://github.com/ethereum/pm/pull/733
Amount: 150/1659 = 0.0904159132
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB

![image](https://user-images.githubusercontent.com/27824858/229350478-8c0c9336-eb52-4436-b392-c6b2a66a7ffa.png)

**Comment by poojaranjan** [comment]
Multisig tx 304 created for #483 #484 #485 #486 #487 #490 #491
Waiting in 2nd approval

**Comment by poojaranjan** [comment]
Tx completed
