### ISSUE TITLE
Funding for EIP editor, (November-March) 2022/2023

### ISSUE THREAD

**Issue by lightclient** [ethereum-cat-herders/funding#488]
Hours: 25*5

Amount: 1660*5 = 8300 USDC

Wallet: 0xdf524fc9b23443de65f5f0695b8c1f86d13e9515

Thank you!

**Comment by poojaranjan** [comment]
Multisig tx 306 created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
Tx completed
