### ISSUE TITLE
$100 funding for ACD Call #80

### ISSUE THREAD

**Issue by sanchaymittal** [ethereum-cat-herders/funding#49]
Meeting: ACD meeting 80
Notes: ethereum/pm#160
Amount: 100 SAI 

Payable to:
sanchaymittal.gitcoin.eth
(0xEab48A633Ada8565f2cdeB5cDE162909Fd64b749)
Thanks!

**Comment by timbeiko** [comment]
First multisig txn sent (#69): 0xfd33a6d9d795ee5876d06624c0b8612d326d0ac05fa363f47940c72d74f1cc9a

@CPSTL @Souptacular @lrettig can you please send the next one? Thanks!

**Comment by CPSTL** [comment]
Confirmed and added to the spreadsheet: https://etherscan.io/tx/0x109786ea37c45cc9805f2ac82f671839e4ee665eef2d9bf907175b8567198ec8
