### ISSUE TITLE
Funding for HIC Feb 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#493]
No. of hrs. = 176 hrs.

Amount = 176*80 = (14080 / $1605.9 ) = 8.7676692 ETH

Wallet = 0xD1C5795353ddD1b3414b4a5dbE583305F943B71c

![Screenshot 2023-04-10 at 10 10 41 PM](https://user-images.githubusercontent.com/97191248/231037365-1e541751-77bc-4eeb-895b-502ba66132ee.png)

**Comment by poojaranjan** [comment]
Multisig tx 311 created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
Tx completed
