### ISSUE TITLE
ECH Ops + Engineering Feb 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#496]
### 1.  ECH website update (Engineering)
[PR](https://github.com/ethereum-cat-herders/ech-website-v2/pulls?q=is%3Apr+author%3ASamarth-001) - 93, 94

Amount = 2 hr @55 USD = 2*55 USD = 110 USD

### 2. ECH video (Ops)
a. Video editing - Ep 99, Ep 100, Ep 101 @ 100 USD each = 300 USD 
b. YouTube Shorts - 4736 shorts, 4337 shorts, Builder API shorts @ 25 USD each = 75 USD
Amount = 375 USD

### 3. ECH Discord & GitPOAP (Engineering)
- User Verification Issue - 3 hrs
- ECH Discord Raid protection - 3.5 hrs
- ECH Discord new bug  - 3.5 hrs
- Wick Bot Issue & enable raid - 2 hrs. 
- GitPOAP - 5 hrs
   - meeting with team
   - Multiple iterations to reach desired file
   - Deployed but team had paused onboarding

Total = 17 hrs @ 55 USD = 935 USD

Total Amount = 110+375+935  USD = 1420 USD = 1420/1605 ETH = 0.88473ETH

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

<img width="566" alt="Screenshot 2023-04-19 at 10 37 15 PM" src="https://user-images.githubusercontent.com/97191248/233243255-45c5e604-4fb2-492f-b9b0-e0b66edd784b.png">

**Comment by poojaranjan** [comment]
multisig tx 312 created, waiting for 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
