### ISSUE TITLE
ECH Ops + Engineering Mar 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#497]
### 1. ECH video
a. Video editing - Ep 102 , Ep 103 @ 100 USD each = 200 USD 
b. YouTube Shorts - Selfdestruct, MEV Boost @ 25 USD each = 50 USD
c. Cover image - Client Diversity @15 USD

### 2. 4337 Telegram and ECH Discord Integration 
(March 25 - 31, 2023)
- DIscord <> Telegram - 6 hrs
- Documentation of 4337 telegram bot  integration - 1.5 hrs
- DIscord <> Telegram Improvisation - 4.5 hrs
 Efforts  = 12 hrs @ 55 USD = 660 USD

Total Amount = 265+660 USD = 925/1822 ETH = 0.50768 ETH

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

<img width="523" alt="Screenshot 2023-04-19 at 10 45 22 PM" src="https://user-images.githubusercontent.com/97191248/233245070-dd12c0b8-3531-42d0-bc80-db5bebb6d77b.png">

**Comment by poojaranjan** [comment]
Multisig tx 317 created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
