### ISSUE TITLE
Event expenses Q1-2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#498]
Location: Denver
Date: Feb 28 - March 03, 2023
User: Pooja Ranjan

<google-sheets-html-origin><style type="text/css"></style>

Event | Accomodation | Air Ticket | Team Dinner | Taxi /Car | Grand Total
-- | -- | -- | -- | -- | --
Denver | $664.54 | $396.40 | $140.00 | $250.32 | $1,451.26

Amount = 1451/1569 ETH = 0.924792 ETH
Wallet: 0xf13e477365B0FAa64130DA2FF663aAb20d32d929

<img width="605" alt="Screenshot 2023-04-20 at 4 06 18 PM" src="https://user-images.githubusercontent.com/97191248/233476185-1b142c65-2987-4418-ad88-9ebed60d2f89.png">

**Comment by poojaranjan** [comment]
multisig tx 314 created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
