### ISSUE TITLE
Funding for HIC Apr 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#500]
No. of hrs. = 176 hrs.

Amount = 176*80 = 14080 USDC

Wallet = 0xD1C5795353ddD1b3414b4a5dbE583305F943B71c

**Comment by poojaranjan** [comment]
Multisig tx 316 created, waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
