### ISSUE TITLE
ECH Engineering (April 2023)

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/funding#501]
The following contributions were completed in the month of April 2023:
- Website
     - Create information page for Dencun upgrade
     - Update home page and navigation

Hours: 2
Amount: 2 * 55/hr = 110 USDC
Wallet: georgeh.eth

**Comment by poojaranjan** [comment]
@geovgy 

please update it to 55 USD/ hour.

**Comment by geovgy** [comment]
Updated. Thanks!

**Comment by poojaranjan** [comment]
multisig tx 318 created, waiting on 2nd approval

**Comment by poojaranjan** [comment]
tx completed!
