### ISSUE TITLE
ECH Ops + Engineering Apr 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#503]
### 1. ECH video
a. Video editing - Ep 104 , Ep 105 @ 100 USD each = 200 USD 
b. YouTube Shorts - 4844(4 shorts)  & 5757 (2 shorts) @ 25 USD each = 150 USD

### 2. 4337 Telegram and ECH Discord Integration 
(April 01-30)
- Discord Wick bot Issue and followed fix - 4 hrs
 Efforts  = 4 hrs @ 55 USD = 220 USD

Total Amount = 200+150+220 USD = 570/1876.92 ETH = 0.303689 ETH

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

![Screenshot 2023-05-04 at 12 43 46 PM](https://user-images.githubusercontent.com/97191248/236270477-1457bcb8-0558-4477-93cc-43874db46452.png)

**Comment by poojaranjan** [comment]
multisig tx 320 created, waiting for 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed!
