### ISSUE TITLE
Funding for: CL Meeting 108 notes

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#505]
https://github.com/ethereum/pm/pull/780
Amount: $150 in eth (0.08161044614)
![image](https://github.com/ethereum-cat-herders/funding/assets/67558925/10a95bff-e44d-4c8a-a216-869df9884b4b)
![image](https://github.com/ethereum-cat-herders/funding/assets/67558925/ce2b2759-76c1-40ad-8679-c3c1d2eb52a0)

Wallet: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94

**Comment by poojaranjan** [comment]
multisig tx created for #505 #513 #514

**Comment by poojaranjan** [comment]
Tx completed!
