### ISSUE TITLE
Funding for the ACDC 109

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#508]
PR: https://github.com/ethereum/pm/pull/785
Amount: 150/1810 = 0.08287292818
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB
![image](https://github.com/ethereum-cat-herders/funding/assets/27824858/01714491-cd53-4b8e-91e5-5601a702d242)

**Comment by poojaranjan** [comment]
multisig tx 325 created for #507 #508 #509 #510

**Comment by poojaranjan** [comment]
Tx completed!
