### ISSUE TITLE
100$ Funding for Notes, ACD 83

### ISSUE THREAD

**Issue by thesachinmittal** [ethereum-cat-herders/funding#51]
Meeting: ACD meeting 83
Notes: ethereum/pm#161
Amount: 100 SAI 

Payable to:
0xd01f31684999d2D5e3925bFb0FaE32f6E359f0fA
Thanks!

**Comment by timbeiko** [comment]
First multisig txn sent (#71): 0xe904cba6c63feb97a3f198397b825f0d34f26ceeb6d7625076600b4187921d0c

@CPSTL @Souptacular @lrettig can you please send the next one? Thanks!

**Comment by thesachinmittal** [comment]
Hey @lrettig @CPSTL @Souptacular any updates on this?

**Comment by CPSTL** [comment]
@thesachinmittal Confirmed 11 days ago: https://etherscan.io/tx/0xc2adc3d45ee5ab9f72e15fe55c2447b4993b3f5516b53c7d1283c9b477276a63
