### ISSUE TITLE
Funding for EL 162 Notes

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#513]
Wallet: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94
Amount: 0.08090614887
https://github.com/ethereum/pm/pull/797 - 90 minutes
![image](https://github.com/ethereum-cat-herders/funding/assets/67558925/d630056b-c6b9-42fe-bdd3-259510605981)
![image](https://github.com/ethereum-cat-herders/funding/assets/67558925/04c96f76-164c-4fbe-adf4-8dc70c6362cd)

**Comment by poojaranjan** [comment]
multisig tx created for #505 #513 #514

**Comment by poojaranjan** [comment]
Tx completed!
