### ISSUE TITLE
Funding for EIPIP 81 notes

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#514]
Amount: 0.05396654074 ETH
Wallet: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94
https://github.com/ethereum-cat-herders/EIPIP/pull/242 - 60 minutes
![image](https://github.com/ethereum-cat-herders/funding/assets/67558925/7cc321e1-1e90-481d-9d28-62de1d8234ec)
![image](https://github.com/ethereum-cat-herders/funding/assets/67558925/eb6f7369-0897-40d1-8538-0b3769ccff0e)

**Comment by poojaranjan** [comment]
multisig tx created for #505 #513 #514

**Comment by poojaranjan** [comment]
Tx completed!
