### ISSUE TITLE
ECH Ops May 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#516]
1. ECH video
a. Video editing - Ep 106 to 109 @ 100 USD each = 400 USD
b. YouTube Shorts - 4804(2 shorts), 5773 (3 shorts), 6672 (2 shorts), 6059 (1 shorts) @ 25 USD each = 8*25 = 200 USD

Total Amount = 400+200 = 600 DAI

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

**Comment by poojaranjan** [comment]
Multisig tx 327 created

**Comment by poojaranjan** [comment]
Tx completed!
