### ISSUE TITLE
Funding for ECH meeting 110 notes

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#517]
Amount: 0.02728602301 ETH
Wallet: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94
PR: https://github.com/ethereum-cat-herders/PM/pull/359 - 30 minutes
![image](https://github.com/ethereum-cat-herders/funding/assets/67558925/2d97b9b9-8758-48c1-8439-63eb332f6d49)
![image](https://github.com/ethereum-cat-herders/funding/assets/67558925/f95e6bdd-bf66-4b2e-81cf-9261780d08ca)

**Comment by poojaranjan** [comment]
Multisig tx 331 initiated for #517 #520. Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
