### ISSUE TITLE
EIPIP meeting 82

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#519]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/243
- Address: `edson.eth` `0xBBAac64b4E4499aa40DB238FaA8Ac00BAc50811B`
- For amount $100 in ETH, 0.0574 ETH

<img width="1344" alt="image" src="https://github.com/ethereum-cat-herders/funding/assets/34966228/15d3c6ac-d634-41ef-bdd7-17694847852b">

**Comment by poojaranjan** [comment]
Multisig tx 332 created. Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
