### ISSUE TITLE
$100 Funding for note-taking of EIPIP call #5

### ISSUE THREAD

**Issue by BrentAllsop** [ethereum-cat-herders/funding#52]
Meeting: EIPIP call #5

Pull Request:
https://github.com/ethereum-cat-herders/EIPIP/pull/9

Notes location: https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20005.md

Amount: 100 SAI

Wallet:
0x49f2aaD7A540c1539824e33114d21ED85674e480

Thanks.

**Comment by timbeiko** [comment]
First multisig txn sent (#72): 0xf9687e1df0781bbd20d2ce6cd7972b931726a286370e918f17b8eeaa8c8612e7

@CPSTL @Souptacular @lrettig can you please send the next one? Thanks!

**Comment by CPSTL** [comment]
Confirmed and added to the spreadsheet: https://etherscan.io/tx/0x97f369ecad8f3b3f055322bfa9442d0f626f3e64d95a9220c86a2f65c157490c
