### ISSUE TITLE
Funding for CL Meeting 111

### ISSUE THREAD

**Issue by darkfire-rain** [ethereum-cat-herders/funding#520]
Wallet: 0x08d13cF98f0a30d60d505d4628F645f65B9C0b94
PR: https://github.com/darkfire-rain/pm/blob/master/AllCoreDevs-CL-Meetings/Call_111.md
Amount in ETH 0.0871
Meeting Duration: 90 minutes
![image](https://github.com/ethereum-cat-herders/funding/assets/67558925/057f65a9-ae03-4e22-ae82-0b4605f7ac1a)
![image](https://github.com/ethereum-cat-herders/funding/assets/67558925/93f0c0e6-1499-4d9a-9800-d7ee4b86685e)

**Comment by poojaranjan** [comment]
Multisig tx 331 initiated for #517 #520. Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed!
