### ISSUE TITLE
ECH Ops June 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#527]
**ECH video**
a. Video editing - Ep 110  @ 100 USD each = 100 USD
b. YouTube Shorts - ERC-6220 (3 shorts), EIP-4844 ( 1 shorts) @ 25 USD each = 4*25 = 100 USD
Total Amount = 100+100 = 200 DAI/USDC

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

**Comment by poojaranjan** [comment]
Multisig tx 335 created for 

- https://github.com/ethereum-cat-herders/funding/issues/527
- https://github.com/ethereum-cat-herders/funding/issues/534

waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
Funds released!
