### ISSUE TITLE
Funding for AllCoreDevsEL Meeting notes #166

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#529]
PR: https://github.com/ethereum/pm/pull/837
Amount: 150/1882 = 0.07970244421
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB
![image](https://github.com/ethereum-cat-herders/funding/assets/27824858/e6eb1501-3d45-4acb-8cdd-b6991d7475ef)

**Comment by poojaranjan** [comment]
Multisig tx 334 created for

- https://github.com/ethereum-cat-herders/funding/issues/524
- https://github.com/ethereum-cat-herders/funding/issues/525
- https://github.com/ethereum-cat-herders/funding/issues/529
- https://github.com/ethereum-cat-herders/funding/issues/530
- https://github.com/ethereum-cat-herders/funding/issues/531

Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
Funds released!
