### ISSUE TITLE
ECH Ops July 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#534]
**ECH video**
a. Video editing

- [Ep 111](https://youtu.be/W_A6qfvOrhw), 
- [Ep 112](https://youtu.be/tRTBgCN9VgY), 
- [Ep 113](https://youtu.be/g47MOV8ETB8), 
- [Ep 114](https://youtu.be/Z4tMgrreCN8) 

@ 100 USD each = 4*100 = 400 USD

b. YouTube Shorts
- [Cross layer EIPs need more coordination](https://youtu.be/s9v2SObVY7I)
- [Single Slot Finality is a really nice improvement](https://youtube.com/shorts/KlZgbFtcdIQ)
- [An amazing Ethereum sooner rather than later](https://youtube.com/shorts/2d-32GZqnco)
- [Let's make a uniform EIP process](https://youtu.be/6gFiyj9ZDkc)
- [Solo Staking on Ethereum blockchain is much simpler](https://youtube.com/shorts/2sMH3Sf9BK8)
- [A shoutout to Ethereum Protocol Fellowship](https://youtube.com/shorts/QcXdz5dgyX0)
- [Ethereum researcher Mikhail Kalinin's message to the community](https://youtube.com/shorts/5GHHrxg4bI0)
- [Denial of Service Analysis on EIP6110 with Peter Davis](https://youtube.com/shorts/-Q0BTrVXaBs)
- [What are blobs per block? ](https://youtube.com/shorts/ZEEpWzkU2HI)
- [Ethereum validator ready for ProposerBuilderSeparations](https://youtube.com/shorts/kERBtKJunMw)

@ 25 USD each = 10*25 = 250 USD

Total Amount = 400+250 = 650 DAI/USDC

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

**Comment by poojaranjan** [comment]
Multisig tx 335 created for

https://github.com/ethereum-cat-herders/funding/issues/527
https://github.com/ethereum-cat-herders/funding/issues/534
waiting on 2nd Confirmation

**Comment by poojaranjan** [comment]
Funds released!
