### ISSUE TITLE
Funding For ECH meeting 114

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#535]
- PR: [ECH Meeting 114](https://github.com/ethereum-cat-herders/PM/pull/368)

- Amount: 50 USDC

- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Multisig tx 337 created for 

- #535 
- #536 
- #538

Waiting on 2nd approval.

**Comment by poojaranjan** [comment]
Tx completed!
