### ISSUE TITLE
Update Finance Spreadsheet

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#54]
[This spreadsheet](https://docs.google.com/spreadsheets/d/1PMCKHrkD2oGNXnDi6chy9DOFbpXgDRqpNz75PXSzoj4/edit#gid=0) needs updating for months following January of this year. 

List of transactions [found here](https://etherscan.io/tokentxns?a=0x68085e7f88e90fa9247489c83fab30b177ebccb3).

**Comment by poojaranjan** [comment]
Created a new [ECH mulitisig accounting sheet](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0) that carries all previous transactions.
