### ISSUE TITLE
Funding for Consensus Layer #117

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/funding#541]
- PR: [Consensus Layer #117](https://github.com/ethereum/pm/pull/872)

- Amount: 150 USDC

- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Multisig tx 342 created for
https://github.com/ethereum-cat-herders/funding/issues/540
https://github.com/ethereum-cat-herders/funding/issues/541
https://github.com/ethereum-cat-herders/funding/issues/543

Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
Tx completed!
