### ISSUE TITLE
ECH Ops Sep 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#544]
#### a. PEEPanEIP 
- [PEEPanEIP #118: EIP-5656: MCOPY - Memory copying instruction](https://youtu.be/m_YzKuL2VxM) 
- [PEEPanEIP #117: EIP-4788:Beacon block root in the EVM with Alex Stokes](https://youtu.be/GriLSj37RdI) 

@ 100 USD each = 2*100 = 200 USD

#### b. YouTube Shorts / Video clips  
- [Got #EVM or #EOF related #EIP or questions, reach team #Ipsilon #vyper](https://youtu.be/mw7ktiOhX-E) 

@ 25 USD each  = 1*25 = 25 USD

#### c. Ecosystem Project Demo (with thumbnail) 
- [Octant: Ecosystem Project Demo #3](https://youtu.be/CX3_B3d83lU) 
- [EIPFun: Ecosystem Project Demo #2](https://youtu.be/kJVXpD2X2e8) 

@ 35 USD each = 2*35 = 70 USD

 ### Figma Design
- ECH webpage [Figma Design - PEEPanEIP page](https://www.figma.com/file/uXsNK9RsQs9xtT71LKsGL0/Ethereum-Cat-Herders?type=design&node-id=18-18&mode=design) 
Hours = 2 

@ 50 USD per hour = 2*50 = 100 USD

Total = 100+70+25+200 = 395 USDC/DAI

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

**Comment by poojaranjan** [comment]
Multisig tx 343 created, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
Tx completed!
