### ISSUE TITLE
Funding for HIC Sep 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#545]
No. of hrs. = 176 hrs.

Amount = 176*80 = 14080 USDC

Funds Requested = 14080-7760 =  6320 USDC

(7760 USDC  is funded via ENS grant )

Wallet = 0xD1C5795353ddD1b3414b4a5dbE583305F943B71c

**Comment by poojaranjan** [comment]
Multisig tx 344 created, waiting on 2nd approval.

**Comment by poojaranjan** [comment]
Tx completed!
