### ISSUE TITLE
Funding For ECH meeting 118

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#546]
PR: https://github.com/ethereum-cat-herders/PM/pull/374

Amount: 50 USDC/DAI

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

**Comment by poojaranjan** [comment]
Multisig tc 3468 created for #546 #560

**Comment by poojaranjan** [comment]
tx completed
