### ISSUE TITLE
Funding for Execution Layer Meeting 172

### ISSUE THREAD

**Issue by Aleneth** [ethereum-cat-herders/funding#548]
PR: https://github.com/ethereum/pm/pull/893
Amount: 150/1674 = 0.08960573477
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB
<img width="1498" alt="image" src="https://github.com/ethereum-cat-herders/funding/assets/145821766/7b445acc-c3c6-452d-bf99-df8c917f4d32">

**Comment by poojaranjan** [comment]
Multisig tx 347 created for 
#548
#549 
#550 
#551 
#552 
#554 
Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed
