### ISSUE TITLE
Funding for Consensus-layer Call 118 

### ISSUE THREAD

**Issue by Aleneth** [ethereum-cat-herders/funding#549]
PR: https://github.com/ethereum/pm/pull/876
Amount: 150/1590 = 0.09433962264
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB
<img width="1513" alt="image" src="https://github.com/ethereum-cat-herders/funding/assets/145821766/908a1ff8-013b-4785-bdf2-7f8fc7a9fb5f">

**Comment by poojaranjan** [comment]
Multisig tx 347 created for 
#548
#549 
#550 
#551 
#552 
#554 
Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed
