### ISSUE TITLE
Funding for Note taking, ECH call #30 and #31

### ISSUE THREAD

**Issue by nglglhtr** [ethereum-cat-herders/funding#55]
- **Meetings**: 
  - Ethereum Cat Herders Meeting 30 (volunteered to take up)
  - Ethereum Cat Herders Meeting 31 (scheduled note-taker)
- **Notes**: https://github.com/ethereum-cat-herders/PM/pull/117
- **Amount**: 100 DAI
- **Wallet**: `0xd01f31684999d2D5e3925bFb0FaE32f6E359f0fA`

Thanks! :bowtie:

**Comment by Souptacular** [comment]
ID #3 on https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions. Waiting on a 2nd person to approve the tx.

**Comment by Souptacular** [comment]
Approved and sent. Closing issue.
