### ISSUE TITLE
Funding for Consensus-layer Call 115

### ISSUE THREAD

**Issue by Aleneth** [ethereum-cat-herders/funding#552]
PR: https://github.com/ethereum/pm/pull/848
Amount: 150/1838 = 0.08161044614
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB
<img width="1491" alt="image" src="https://github.com/ethereum-cat-herders/funding/assets/145821766/c7bc8694-89e9-4681-8107-f484a5c7a984">

**Comment by poojaranjan** [comment]
Multisig tx 347 created for 
#548
#549 
#550 
#551 
#552 
#554 
Waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed
