### ISSUE TITLE
Funding for note-taking of All Core Devs Meeting 85 

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#56]
Meeting: All Core Devs Meeting 85 

PR location: https://github.com/ethereum/pm/pull/166

Amount: 100 SAI/DAI

Wallet: (ranjan.eth)
0xf13e477365B0FAa64130DA2FF663aAb20d32d929

Thanks.

**Comment by Souptacular** [comment]
ID 5 on https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions. Waiting for a 2nd owner to execute.

**Comment by poojaranjan** [comment]
Received, thanks!
