### ISSUE TITLE
ECH Ops Oct 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#561]
#### a. PEEPanEIP 
- [PEEPanEIP #119: EIP-7514: Add Max Epoch Churn Limit with Dapplion](https://youtu.be/URQZVqgKZI4)
- [PEEPanEIP #120: Holešky Holešovice #testnet with Afri, Pari, Barnabas, Philipp](https://youtu.be/2tZE88iFCq4)
- [PEEPanEIP #121: EVM Object Format (EOF) with Danno Ferrin](https://youtu.be/rlZwPuF149U)
@ 100 USD each = 3*100 = 300 USD

#### b. YouTube Shorts / Video clips  
- [Stay tuned for more to come in #Ethereum!](https://youtube.com/shorts/P92pBBVJyrI)
- [Why EIP-7441: Upgrade block proposer election to Whisk is important?](https://youtube.com/shorts/Pq5AwswMsVE)
- [PEEPanEIP is fantastic-Dapplion](https://youtube.com/shorts/pJeC7MklEbA)
- [EOF proposed changes to #evm  #ethereum](https://youtube.com/shorts/xqM74oBE63Y)
@ 25 USD each  = 4*25 = 100 USD

#### c. Ecosystem Project Demo (with thumbnail) 
- [SafeStack: Ecosystem Project Demo #4](https://youtu.be/1FWpytrpYU0)
@ 35 USD each = 1*35 = 35 USD

 ### Figma Design
- [Testnet Page design & research content for page wrt each testnet](https://www.figma.com/file/uXsNK9RsQs9xtT71LKsGL0/Ethereum-Cat-Herders?type=design&node-id=327-78&mode=design)
Hours = 4 

@ 50 USD per hour = 4*50 = 200 USD

Total = 300+100+35+200 = 635 USDC/DAI

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

**Comment by poojaranjan** [comment]
multisig tx 350 created, waiting on 2nd confirmation.

**Comment by poojaranjan** [comment]
tx completed
