### ISSUE TITLE
Funding for EIPIP-93

### ISSUE THREAD

**Issue by Aleneth** [ethereum-cat-herders/funding#562]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/294
Amount: 100/2096 = 0.04770992366
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB
<img width="1512" alt="image" src="https://github.com/ethereum-cat-herders/funding/assets/145821766/2ee91794-309f-4e98-bfe3-e0103cd39251">

**Comment by poojaranjan** [comment]
tx completed
