### ISSUE TITLE
Funding for ACDE Meeting 174

### ISSUE THREAD

**Issue by TeamAvarch** [ethereum-cat-herders/funding#566]
PR: https://github.com/ethereum/pm/pull/903

Amount: 150 USDC/DAI

Wallet: 0x848e313d4b25bC0B48CaFdB6A72391E892E6A247

**Comment by poojaranjan** [comment]
multisig tx 354 created. waiting for 2nd Confirmation

**Comment by poojaranjan** [comment]
tx completed
