### ISSUE TITLE
Funding for CL 122

### ISSUE THREAD

**Issue by Aleneth** [ethereum-cat-herders/funding#567]
PR: https://github.com/ethereum/pm/pull/911
Amount: 150/2021 = 0.07422068283
Wallet: 0x1218bbD14789E29acc0e788779eA0397BE9FFfdB
<img width="1507" alt="image" src="https://github.com/ethereum-cat-herders/funding/assets/145821766/1cf7e5f7-17b5-4eb7-81a6-ead98ec2012a">

**Comment by poojaranjan** [comment]
multisig tx 355 created for 
#562
#563 
#564
#565 
#567 

Waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed
