### ISSUE TITLE
Funding for notes, ECH #32

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#57]
Funding required for ECH call 32 ([PR](https://github.com/ethereum-cat-herders/PM/pull/120)).

- Payable to `edson.eth`
- For amount 50 DAI/USDC

**Comment by Souptacular** [comment]
Sent 50 USDC request. ID 6 on https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions.

**Comment by edsonayllon** [comment]
Got it.

**Comment by poojaranjan** [comment]
Added to the new [ECH mulitisig accounting sheet](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0)
