### ISSUE TITLE
ECH Ops Nov 2023

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#571]
#### a. PEEPanEIP 
- [PEEPanEIP #122: EIP-7516: BLOBBASEFEE opcode with Ansgar Dietrichs](https://youtu.be/VUita9Yl9gY)
- [PEEPanEIP #123: EIP-4881: Deposit Contract Snapshot Interface](https://youtu.be/GzQSVdTwAa0)
- [PEEPanEIP #124: EIP-5069: EIP Editor Handbook with Sam Wilson](https://youtu.be/FFl1HxbZ-K8)

@ 125 USD each = 3*125 = 375 USD

#### b. YouTube Shorts / Video clips  
- [Let's do Mega EOF asap evm ](https://youtube.com/shorts/xqM74oBE63Y?feature=share)
- [Ethereum transaction will slightly go cheaper with eip4844 & eip7516 on Dencun](https://youtu.be/0Vsu7cKbGxY)
- [RollCall Meetings for Layer 2 Projects](https://youtu.be/fezITtco2JU)
- [Ethereum's Optimistic Roadmap with ethDreamer](https://youtube.com/shorts/W9Mu_-qsJeA)
- [Read proposals, add review comments & align with ethereum](https://youtube.com/shorts/C1FdWEJSs8U)

@ 25 USD each  = 5*25 = 125 USD

#### c. Meet The Herders (with thumbnail)
- [Meet The Herders #1: Pooja Ranjan ](https://youtu.be/XCOdX5UmtU4)
- [Meet The Herders #2: Victor Zhou ](https://youtu.be/5k3X4MJPZU0)

@ 100 USD each = 2*100 = 200 USD

 ### Figma Design
- [Testnet Page design & research content for page wrt each testnet](https://www.figma.com/file/uXsNK9RsQs9xtT71LKsGL0/Ethereum-Cat-Herders?type=design&node-id=531-2&mode=design)
Hours = 2 

@ 55 USD per hour = 2*55 = 110 USD

Total = 375+125+200+110 = 810 USDC/DAI

Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

**Comment by poojaranjan** [comment]
multisig tx 356 created. waiting on 2nd confirmation

**Comment by poojaranjan** [comment]
tx completed
