### ISSUE TITLE
Zoom account renewal

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/funding#59]
Requesting 149.90 DAI paid to lanechain.eth. Invoice attached. Cf. ethereum-cat-herders/PM#115.

![image](https://user-images.githubusercontent.com/3316532/81009169-1f193780-8e22-11ea-8e5d-35daabf6c4ff.png)

**Comment by Souptacular** [comment]
Sent tx for approval. It is ID 11: https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by lrettig** [comment]
This came through. Thanks folks! https://etherscan.io/tx/0x068972f3d8053ff7c8f3a80aabeffb78c83c9f51c6a00fc9dc22467a6f0a8b63
