### ISSUE TITLE
Reimbursement for Funding the Note Taker Bounty for AllCoreDevs Meeting #58

### ISSUE THREAD

**Issue by CPSTL** [ethereum-cat-herders/funding#6]
**Here is the transaction for the bounty payout:** https://etherscan.io/tx/0x2cb58328381a08d213ea0dde9c94d9ffe8f84dcc15d19a9ba8d2d97989bd1aed

**Please reimburse to the following address:** 0x2806c443cFd1E492323de4ebB6404689231cA506

**Gitcoin Issue Bounty (for reference):** https://gitcoin.co/issue/ethereum-cat-herders/PM/21/2642

**Comment by lrettig** [comment]
Approved. I submitted a 50 DAI withdrawal tx to the multisig for this (https://etherscan.io/tx/0xc7b72353db03c67e1f7c71878f3b1ccfe1e3df624eec087c01b5ee2c9eaaf417). @Souptacular could you please double-check everything (amount, destination, etc.) and if so, submit the second approval? It's tx no. 12 in the multisig. Thanks!

**Comment by CPSTL** [comment]
Thanks, @lrettig @Souptacular :)

**Comment by lrettig** [comment]
@Souptacular confirmed this, thanks! https://etherscan.io/tx/0x883890ec2e7f4de302f37c7438d57898bb062b221fca6d06adc84c0adbfeabb8
