### ISSUE TITLE
Funding for notes, ECH #34

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#62]
Meeting: ECH #34

Notes location: https://github.com/ethereum-cat-herders/PM/blob/master/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%20034.md

Amount: 50 DAI/USDC

Wallet: (ranjan.eth)
0xf13e477365B0FAa64130DA2FF663aAb20d32d929

Thanks.

**Comment by timbeiko** [comment]
Transfer #45 in the multisig awaiting confimation to send 250 DAI for:
* https://github.com/ethereum-cat-herders/funding/issues/62
* https://github.com/ethereum-cat-herders/funding/issues/66
* https://github.com/ethereum-cat-herders/funding/issues/68

**Comment by lrettig** [comment]
Just confirmed and executed this: https://etherscan.io/tx/0x0648d592afddb25a65a0c914468751b89bf88405c403b39c06c0d46d6ad28662
