### ISSUE TITLE
Funding notes for EIP IP #7

### ISSUE THREAD

**Issue by BrentAllsop** [ethereum-cat-herders/funding#64]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/14

Payable to: 0xED4aD2e886C5c31D298d1de49256C40239180D16
For amount 100 DAI/USDC

**Comment by timbeiko** [comment]
Transfer 46 in the multisig to send 250 DAI for these notes: 
* https://github.com/ethereum-cat-herders/funding/issues/72
* https://github.com/ethereum-cat-herders/funding/issues/64
* https://github.com/ethereum-cat-herders/funding/issues/65

**Comment by poojaranjan** [comment]
Details added to the [ECH Multisig](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0). 

Please confirm the receipt and close the issue. Thanks!

**Comment by BrentAllsop** [comment]
Confirmed Received.
