### ISSUE TITLE
Funding for notes, ACD #87

### ISSUE THREAD

**Issue by BrentAllsop** [ethereum-cat-herders/funding#65]
Pull Requests:
https://github.com/ethereum/pm/pull/177
https://github.com/ethereum/pm/pull/179

Payable to: 
0xED4aD2e886C5c31D298d1de49256C40239180D16

Amount: 100 DAI/USDC

**Comment by timbeiko** [comment]
Transfer 46 in the multisig to send 250 DAI for these notes: 
* https://github.com/ethereum-cat-herders/funding/issues/72
* https://github.com/ethereum-cat-herders/funding/issues/64
* https://github.com/ethereum-cat-herders/funding/issues/65

**Comment by poojaranjan** [comment]
Details added to the [ECH Multisig](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0). 

Please confirm the receipt and close the issue. Thanks!

**Comment by BrentAllsop** [comment]
Confirmed Received.
