### ISSUE TITLE
Funding for notes EIPIP #9 

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#66]
**Meeting**: EIPIP #9 

**Notes location**: https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20009.md

**Amount**: 100 DAI/USDC

**Wallet**: (ranjan.eth)
0xf13e477365B0FAa64130DA2FF663aAb20d32d929

Thanks.

**Comment by timbeiko** [comment]
Transfer 45 in the multisig awaiting confimation to send 250 DAI for:
* https://github.com/ethereum-cat-herders/funding/issues/62
* https://github.com/ethereum-cat-herders/funding/issues/66
* https://github.com/ethereum-cat-herders/funding/issues/68

**Comment by poojaranjan** [comment]
Added to the [ECH multisig sheet](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0).
