### ISSUE TITLE
Funding for notes ACD #88

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#67]
**Meeting**: ACD #88

**Notes**: https://github.com/ethereum/pm/tree/master/AllCoreDevsMeetings/Meeting88.md

(not yet merged as I'm writing this, that should be the location)

**Amount**: 100 DAI

**Address**: wschwab.eth

Cheers!

**Comment by wschwab** [comment]
Apparently I had formatted the link wrong - the notes are at https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2088.md

Is there any additional action I need to take?

**Comment by wschwab** [comment]
As per ECH meeting 36, it was decided that note-takers could request payment in ETH (as opposed to DAI), and be paid $100 of ETH using the price of ETH at the time of merging the notes.

My [PR](https://github.com/ethereum/pm/pull/182) was merged at 1802 UTC June 10. I used the resource at [ethereumprice.org](https://ethereumprice.org) to determine that the price at the time (1800 UTC) was $243.40/ETH (screenshot included, note the price on the line, not the price on top, which was the price of ETH current to the screenshot). If I'm doing my math right, that should be 0.411522634 ETH.

The receiving address should still be wschwab.eth

Thanks!

![eth_price](https://user-images.githubusercontent.com/31592931/85418356-5af69080-b579-11ea-8767-cbd5e5b63af6.png)

**Comment by timbeiko** [comment]
Transaction 47 in the multisig needs approval to send 0.411522634 ETH for these notes.

**Comment by poojaranjan** [comment]
Tx: 0x5674d8b824bd59d9b46d367231244301ab0a01e365c4819976834882a673a93d

Details added to the [ECH Multisig](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0). 

Please confirm the receipt and close the issue. Thanks!

**Comment by wschwab** [comment]
Confirmed. Thank you!
