### ISSUE TITLE
Funding for notes ACD #89

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#68]
**Meeting**: ACD #89 

**Notes PR**: https://github.com/ethereum/pm/pull/183

**Amount**: 100 DAI/USDC

**Wallet**: (ranjan.eth)
0xf13e477365B0FAa64130DA2FF663aAb20d32d929

Thanks.

**Comment by timbeiko** [comment]
Transfer #45 in the multisig awaiting confimation to send 250 DAI for:
* https://github.com/ethereum-cat-herders/funding/issues/62
* https://github.com/ethereum-cat-herders/funding/issues/66
* https://github.com/ethereum-cat-herders/funding/issues/68

**Comment by poojaranjan** [comment]
Added to the [ECH multisig sheet](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0).
