### ISSUE TITLE
Funding for Notes, ECH #35

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/funding#69]
PR: https://github.com/ethereum-cat-herders/PM/pull/125

- Payable to `edson.eth`
- For amount 50 DAI/USDC

**Comment by timbeiko** [comment]
Transaction 48 in the multisig needs confirmation for 250 DAI for these notes: 
* https://github.com/ethereum-cat-herders/funding/issues/69
* https://github.com/ethereum-cat-herders/funding/issues/70
* https://github.com/ethereum-cat-herders/funding/issues/73

**Comment by poojaranjan** [comment]
Tx: https://etherscan.io/tx/0xad87b0b19127e7315a648ae61a9c5f37e76a93892ca50291208b409aaca1429f

Details added to the [ECH Multisig](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0). 

Please confirm the receipt and close the issue. Thanks!
