### ISSUE TITLE
Bounty for note-taking for core devs meetings #59, #60

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/funding#7]
- Meeting 59: @poojaranjan at https://github.com/ethereum/pm/pull/94
- Meeting 60: @DBrettRobertson at https://github.com/ethereum/pm/pull/96

Could someone please approve a 50 DAI payout for each of these? (We're catching up here so let's just bypass gitcoin for now.)

**Comment by CPSTL** [comment]
Approved. Setting up the transactions now.

**Comment by lrettig** [comment]
@CPSTL submitted these to the multisig and I confirmed:

- (to @poojaranjan) https://etherscan.io/tx/0x7b7d4c5e236b2179fa7cdf79d4c967ce92e23aaf2d91fac1e69da4ca39f3547f
- (to @DBrettRobertson) https://etherscan.io/tx/0x725e9dde37d908124ccf35bf76342e8d923d9c414ccf8170656a58789cc6a241

Will let Charles update the accounting spreadsheet.
