### ISSUE TITLE
Funding for notes, ETH2 #42

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#71]
PR: https://github.com/ethereum/eth2.0-pm/pull/163

address: wschwab.eth
amount: As per the screenshots below (note the time in the bar on the top), ETH was 234.16 around when I pushed the PR, which would make 100 DAI = 0.426511985 ETH, by my calculations. I'd prefer ETH to DAI.

![thurs_eth_price](https://user-images.githubusercontent.com/31592931/85788918-6347fa80-b736-11ea-9d0a-8d8a4c5057d6.png)
![pr_time_proof](https://user-images.githubusercontent.com/31592931/85788923-65aa5480-b736-11ea-81c8-5569445bbd0c.png)

**Comment by poojaranjan** [comment]
For Eth2 meeting notes, please open funding issue [here](https://github.com/ethereum/eth2.0-pm/issues). Thanks!
