### ISSUE TITLE
$50 Funding for ECH Meeting #36

### ISSUE THREAD

**Issue by BrentAllsop** [ethereum-cat-herders/funding#72]
$50 for taking notes for ECH Meeting #36.

Here is the pull request:
https://github.com/ethereum-cat-herders/PM/pull/127

Deposit Address:
0xED4aD2e886C5c31D298d1de49256C40239180D16

**Comment by timbeiko** [comment]
Transfer 46 in the multisig to send 250 DAI for these notes: 
* https://github.com/ethereum-cat-herders/funding/issues/72
* https://github.com/ethereum-cat-herders/funding/issues/64
* https://github.com/ethereum-cat-herders/funding/issues/65

**Comment by poojaranjan** [comment]
Details added to the [ECH Multisig](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0). 

Please confirm the receipt and close the issue. Thanks!

**Comment by BrentAllsop** [comment]
Confirmed, received
