### ISSUE TITLE
Funding for notes, ECH #37

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#75]
**Meeting**: ECH #37

**Notes location**: https://github.com/ethereum-cat-herders/PM/blob/master/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%20037.md

**Amount**: 0.21135 ETH / 50 DAI

![Screen Shot 2020-07-09 at 4 21 25 PM](https://user-images.githubusercontent.com/29681685/87087136-8d9ebb00-c200-11ea-89fe-aeac727e3188.png)

![Screen Shot 2020-07-09 at 4 22 08 PM](https://user-images.githubusercontent.com/29681685/87087172-a018f480-c200-11ea-8b31-45bdb13f958f.png)

![Screen Shot 2020-07-09 at 4 26 19 PM](https://user-images.githubusercontent.com/29681685/87087383-f9812380-c200-11ea-8b9d-fee6b487b131.png)

**Wallet**: ranjan.eth

Thanks!

**Comment by Souptacular** [comment]
Do you want it in ETH or DAI?

**Comment by Souptacular** [comment]
Do you want it in ETH or DAI?

**Comment by poojaranjan** [comment]
ETH would be good, thanks!

**Comment by Souptacular** [comment]
Bundled 3 payouts for Pooja:

ECH #37 - 0.21135 ETH
ECH #44 - 0.35 ETH
EIPIP #13 - 0.30 ETH

Total: 0.86135 ETH

Transaction #68 - https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by poojaranjan** [comment]
Added to the [ECH multisig sheet](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0).
