### ISSUE TITLE
Funding for notes, ACD #91

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#76]
**Meeting**: ACD #91

**PR location**: https://github.com/ethereum/pm/pull/193

**Amount**: 0.42345 ETH / 100 DAI

![Screen Shot 2020-07-11 at 12 44 10 PM](https://user-images.githubusercontent.com/29681685/87229325-1d657600-c375-11ea-8c3e-934c3476086c.png)
![Screen Shot 2020-07-11 at 12 54 42 PM](https://user-images.githubusercontent.com/29681685/87229421-cb712000-c375-11ea-8b51-cb8e173059bd.png)
![Screen Shot 2020-07-11 at 12 47 17 PM](https://user-images.githubusercontent.com/29681685/87229326-1e96a300-c375-11ea-8ee6-82028b36e55d.png)

**Wallet**: ranjan.eth

Thanks!

**Comment by Souptacular** [comment]
Do you want it in ETH or DAI?

**Comment by poojaranjan** [comment]
ETH would be good, thanks!

**Comment by Souptacular** [comment]
Transaction #70 of the multi-sig created. Still needs a 2nd signer: https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by poojaranjan** [comment]
Funds received. 
TX: https://etherscan.io/tx/0x2aa120aa87336631adddcdf34ba5620f19172129cf5728be397f34388202c561
Thanks!
