### ISSUE TITLE
Funding for notes, Eth2 #44

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#77]
**Meeting**: Eth2 #44 

**PR location**: https://github.com/ethereum/eth2.0-pm/pull/170

**Amount**: 0.35 ETH / 100 DAI

![Screen Shot 2020-07-27 at 2 19 14 PM](https://user-images.githubusercontent.com/29681685/88577014-56a81200-d014-11ea-918b-361126e0ee80.png)

**Wallet**: ranjan.eth

Thanks!

**Comment by Souptacular** [comment]
Do you want it in ETH or DAI?

**Comment by poojaranjan** [comment]
ETH would be good, thanks!

**Comment by Souptacular** [comment]
Bundled 3 payouts for Pooja:

ECH #37 - 0.21135 ETH
ECH #44 - 0.35 ETH
EIPIP #13 - 0.30 ETH

Total: 0.86135 ETH

Transaction #68 - https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by poojaranjan** [comment]
Added to the [ECH multisig sheet](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0).
