### ISSUE TITLE
Funding for notes, EIPIP #13

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#79]
**Meeting**: EIPIP #13

**Notes location**: https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20013.md

**Amount**: 0.30 ETH / 100 DAI

![Screen Shot 2020-07-30 at 10 27 35 PM](https://user-images.githubusercontent.com/29681685/88994044-75790380-d2b5-11ea-87ef-3879673aad47.png)

**Wallet**: ranjan.eth

Thanks!

**Comment by Souptacular** [comment]
Do you want it in ETH or DAI?

**Comment by poojaranjan** [comment]
ETH would be good, thanks!

**Comment by Souptacular** [comment]
Bundled 3 payouts for Pooja:

ECH #37 - 0.21135 ETH
ECH #44 - 0.35 ETH
EIPIP #13 - 0.30 ETH

Total: 0.86135 ETH

Transaction #68 - https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by poojaranjan** [comment]
Added to the [ECH multisig sheet](https://docs.google.com/spreadsheets/d/1bIGuWehKtFVvtXmfNwvNQGy-jUdhrONqO-yhipdFUR8/edit#gid=0).
