### ISSUE TITLE
Zoom Pro account

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/funding#8]
We need our own Zoom Pro account to host and facilitate meetings. Google Hangouts/Meet is limited to ~10 participants and audio/video quality is not as high. I've tried many other apps including Jitsi and not had very good experiences. We've been using Zoom for a couple of years for the core devs and other meetings and have had a good experience.

The cost is US $14.99 billed monthly or $12.49 per month for a year ($149.90 billed annually). I think we should just sign up for the annual plan, and set up a user account for each herder under the account.

Could someone approve a 150 DAI withdrawal to cover this cost? I will set up the account.

**Comment by DBrettRobertson** [comment]
I think this is a good idea perhaps we can vote on this in the the Ethereum Cat Herders Aragon DAO?

**Comment by lrettig** [comment]
This was approved during the [last meeting](https://github.com/ethereum-cat-herders/PM/blob/master/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%2011.md). I signed up for the pro account. Working on switching it to a shared email address (but for billing purposes it does need to be tied to someone's name and address).

Could someone please review and approve a withdrawal of 163.20 DAI to cover the cost for one year? Thanks.

![image](https://user-images.githubusercontent.com/3316532/57080011-a425ba00-6cbf-11e9-89ac-893d0066dd1b.png)

**Comment by lrettig** [comment]
Email address for the account has been changed to the new shared account ethereumcatherders@gmail.com that @DBrettRobertson set up. Access to this account will be communicated on another channel.

**Comment by DBrettRobertson** [comment]
Approved for funding.

**Comment by lrettig** [comment]
Thanks! @CPSTL @Souptacular could one of you please initiate a tx from the multisig to 0x17CA7E4f40Ce8CBAE4F323a9F6bC8CF5109d5C37?

**Comment by Souptacular** [comment]
Before we pay this out we will need to convert some of the ether and other coins to DAI since we are low on DAI if we are using at least 15k DAI for the audit.

**Comment by lrettig** [comment]
We should have more DAI than we do, according to the [grant page](https://gitcoin.co/grants/82/official-progpow-technical-audit-funding). Logged https://github.com/gitcoinco/web/issues/4362 to investigate.

**Comment by lrettig** [comment]
This went through a few days ago, thanks! I updated the accounting spreadsheet as well. https://etherscan.io/tx/0x1f60c02bba7a31b2f9014986256d69f16ef3957c006cdbfd89e62e0319d6fe50
