### ISSUE TITLE
Funding for notes, EIPIP #12

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#81]
PR: https://github.com/ethereum-cat-herders/EIPIP/pull/24#event-3598185988

For amount: 100 DAI/USDC
Payable to: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by Souptacular** [comment]
Bundling 2 payouts for Alita:

100 DAI for EIPIP #12 & 50 DAI for ECH #38.

Total: 150 DAI

Tansaction #69 - https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions
