### ISSUE TITLE
Funding for ETH 2.0 meeting 45 notes

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#85]
PR: https://github.com/ethereum/eth2.0-pm/pull/172

For amount: 0.25 ETH (== 100DAI as of Aug 9, 6:10 AM UTC)
Payable to: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Please add the snapshot for a quick reference. (Ref: https://github.com/ethereum-cat-herders/funding/issues/86)

**Comment by poojaranjan** [comment]
Bundling 2 payouts for Alita:

0.25 ETH for #85 & 0.248 ETH for ECH #91.

Total: 0.498 ETH

Multisig Transaction 78 - https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by Souptacular** [comment]
Transaction approved. Closing issue.
