### ISSUE TITLE
Funding for notes, ACD #93

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#86]
Meeting: ACD #93

PR location: https://github.com/ethereum/pm/pull/198

Amount: 0.25363973 ETH 

Proof of price:
Time of PR: Aug 10 10:21 AM (PR 4 minutes ago in screenshot, clock time on top bar)
![pr_acd_93](https://user-images.githubusercontent.com/31592931/89759934-e4472f80-daf3-11ea-8c94-2afa468c5893.png)

Price: 1 ETH = $394.26, 100/394.26 = 0.25363973
![uniswap_eth_price](https://user-images.githubusercontent.com/31592931/89760004-09d43900-daf4-11ea-8f76-44b5bd8673ef.png)

Thanks!

**Comment by poojaranjan** [comment]
Bundling 2 payouts for William:

0.2536 ETH for #86 & 0.2492 ETH for #90.

Total: 0.5028 ETH

Multisig Transaction 79 - https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by wschwab** [comment]
Received. Thanks!

Closing.
