### ISSUE TITLE
Funding for note-taking for core devs call #61

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/funding#9]
50 DAI to @poojaranjan for notes taken and PRed here: https://github.com/ethereum/pm/pull/101.

Could someone please approve?

Thanks!

**Comment by lrettig** [comment]
@poojaranjan could you please post Eth address for payment here? Thanks!

**Comment by poojaranjan** [comment]
0xf13e477365B0FAa64130DA2FF663aAb20d32d929

**Comment by lrettig** [comment]
Submitted tx 17 to multisig, @CPSTL / @Souptacular could you please double-check it and then confirm? Thanks

**Comment by CPSTL** [comment]
Confirmed.

**Comment by lrettig** [comment]
Let's keep these open until they've been recorded in the accounting spreadsheet

**Comment by lrettig** [comment]
Confirmed that this was added to the spreadsheet, thanks!
