### ISSUE TITLE
Funding for notes, Eth2 #46

### ISSUE THREAD

**Issue by wschwab** [ethereum-cat-herders/funding#90]
PR: https://github.com/ethereum/eth2.0-pm/pull/177

- amount: 0.2492 ETH (equal to 100 DAI at the time of PR, proof below)
- payable to: wschwab.eth

Proof of Price:
screenshot of PR (note GitHub interface "commented now", and time at top bar):
![pr_eth2_46](https://user-images.githubusercontent.com/31592931/91064242-aee42b00-e637-11ea-98bd-386cca936faa.png)

screenshot of `uniswap.info` for ETH price (note time from top bar):
![eth_price_eth2_46](https://user-images.githubusercontent.com/31592931/91064311-c3c0be80-e637-11ea-90b1-f8a59d18f43c.png)

100 / 401.32 = 0.2492 (a simple sanity check is that if ETH is $400, then 100 DAI = 0.25 ETH, and ETH is just a little stronger (i.e. worth more DAI) here)

**Comment by poojaranjan** [comment]
Bundling 2 payouts for William:

0.2536 ETH for #86 & 0.2492 ETH for #90.

Total: 0.5028 ETH

Multisig Transaction 79 - https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by wschwab** [comment]
Received. Thanks!

Closing.

Note: You may want to mention the tx hash - they make it much easier to double-check. Mine this time was 0xf36f022c1b13d04a0c501087bee14205c9c46b8fb41c4f6f24bc6016a3cf94cc
