### ISSUE TITLE
all core devs 94

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#91]
PR: https://github.com/ethereum/pm/pull/201

For amount: 0.248820 ETH ($100)
Payable to: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by poojaranjan** [comment]
Bundling 2 payouts for Alita:

0.25 ETH for #85 & 0.248 ETH for #91.

Total: 0.498 ETH

Multisig Transaction 78 - https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by Souptacular** [comment]
Funds approved. Closing issue.
