### ISSUE TITLE
Funding for Herder-in-chief Aug 2020

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#92]
**August 2020**

- Week 1: 20 hrs. 
- Week 2: 20 hrs.
- Week 3: 20 hrs.
- Week 4: 20 hrs.
- Week 5: 4 hrs.

**Amount**: 84 hrs X 57 DAI per hr = 4788 DAI

**Wallet**: ranjan.eth
0xf13e477365B0FAa64130DA2FF663aAb20d32d929

Thanks!

**Comment by poojaranjan** [comment]
Bundling 2 payouts

4788 DAI for #92.   
100 DAI for #93  

Total = 4888 DAI

Multisig transaction: 81 - https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by Souptacular** [comment]
Funds approved. Closing issue.
