### ISSUE TITLE
Funding for notes, 1559 implementers meeting #04

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#93]
**Meeting**: 1559 Implementers' meeting

**Notes location**: https://github.com/ethereum/pm/blob/master/Fee%20Market%20Meetings/Meeting%2004.md

**Amount**: 100 DAI

**Wallet**: ranjan.eth
0xf13e477365B0FAa64130DA2FF663aAb20d32d929

Thanks!

**Comment by poojaranjan** [comment]
Bundling 2 payouts

4788 DAI for #92.   
100 DAI for #93  

Total = 4888 DAI

Multisig transaction: 81 - https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/transactions

**Comment by Souptacular** [comment]
Funds approved. Closing issue.
