### ISSUE TITLE
Funding for ECH 41 & EIPIP 16

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/funding#96]
PRs

[ECH](https://github.com/ethereum-cat-herders/PM/pull/136)
[EIPIP](https://github.com/ethereum-cat-herders/EIPIP/pull/32)

![EIPIP](https://imgur.com/Y4HJoYw.png)
![ECH](https://imgur.com/boLzPTN.png)

Amount: 0.404 ETH

![eth](https://imgur.com/4WWxC2K.png)

ETH address: 0x680F1956E953FCb5C3774fC4a0Bee5504D179942

**Comment by timbeiko** [comment]
Signed txn 84 in the multisig for this.

**Comment by poojaranjan** [comment]
Transaction completed, multisg account sheet updated.
