### ISSUE TITLE
Funding for 1559 outreach (Aug 29- Sep 15)

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#99]
**For**: 1559 outreach efforts (biweekly submission)

**Effort**: 17.5 hrs

**Amount**: 875 DAI

**Ref**: 
- Document: https://docs.google.com/document/d/1PHrFkPWHkCspLD4R06pg7DaXvCJ1_ZDmR_7VC28y-rk/edit
- Sheet: https://docs.google.com/spreadsheets/d/1z5VMyNKbIdvdo-N7VMb8AIeQgy8SvewKSdf0fAzqp9w/edit#gid=0

**Wallet**: 0x219a6150076E847e678031482f9d130b5Bef5932

cc: @timbeiko

**Comment by timbeiko** [comment]
Signed txn 82 in the multisig for this

**Comment by poojaranjan** [comment]
Funds received, multisig udated.
